### DISCUSSION TITLE
[HELP] Can you help me to Bunkerized Pwndoc ?

### DISCUSSION THREAD

**Discussion by Sorrow81** [bunkerity/bunkerweb#246] [Help]
Hello, i want to bunkerized Pwndoc : https://github.com/pwndoc/pwndoc

Pwndoc is a website to manage pentest. Actually when i try to bunkerized this, i'm able to reach pwndoc when i specify port 8443 in url. My REDIRECT_HTTP_TO_HTTPS is working.

I tries many things without success.

I think [nginx.conf](https://github.com/pwndoc/pwndoc/blob/master/frontend/.docker/nginx.conf)  is my problems, but i can't solve it.

**How to reproduce**
Clone repository pwndoc
`git clone https://github.com/pwndoc/pwndoc.git pwndoc.sorrow.local`

Edit docker-compose.yml

`cd pwndoc.sorrow.local`
`nano docker-compose.yml`

```yaml
#/home/sorrow/vps/www/pwndoc.sorrow.local/docker-compose.yml
version: '3'
services:
  mongodb:
    image: mongo:4.2.15
    container_name: mongo-pwndoc
    volumes:
      - ./backend/mongo-data:/data/db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_DB:pwndoc
    networks:
      - services-net

  pwndoc-backend:
    build: ./backend
    image: yeln4ts/pwndoc:backend
    container_name: pwndoc-backend
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
    depends_on:
      - mongodb
    restart: always
    ports:
      - 4242:4242
    links:
      - mongodb
    networks:
      services-net:
        aliases:
          - pwndoc-backend
    labels:
      - "bunkerized-nginx.SERVER_NAME=pwndocbackend.sorrow.local" # replace with your domain
      - "bunkerized-nginx.USE_REVERSE_PROXY=yes"
      - "bunkerized-nginx.REVERSE_PROXY_URL=/"
      - "bunkerized-nginx.REVERSE_PROXY_HOST=https://pwndoc-backend:4242"
      - "bunkerized-nginx.USE_BAD_BEHAVIOR=no"
      - "bunkerized-nginx.REDIRECT_HTTP_TO_HTTPS=yes"

  pwndoc-frontend:
    build: ./frontend
    image: yeln4ts/pwndoc:frontend
    container_name: pwndoc-frontend
    restart: always
    ports:
      - 8443:8443
    networks:
      services-net:
        aliases:
          - pwndoc-frontend
    labels:
      - "bunkerized-nginx.SERVER_NAME=pwndocfrontend.sorrow.local" # replace with your domain
      - "bunkerized-nginx.USE_REVERSE_PROXY=yes"
      - "bunkerized-nginx.REVERSE_PROXY_URL=/"
      - "bunkerized-nginx.REVERSE_PROXY_HOST=https://pwndoc-frontend:8443"
      - "bunkerized-nginx.USE_BAD_BEHAVIOR=no"
      - "bunkerized-nginx.REDIRECT_HTTP_TO_HTTPS=yes"

volumes:
  mongo-data:

networks:
  services-net:
    external:
      name: services-net
```

Create bunkerized autoconf

`cd ../..`
`nano docker-compose.yml`

```yaml
#/home/sorrow/vps/docker-compose.yml
version: '3'

services:

  mybunkerized:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      #- 443:8443
    volumes:
      #- ./certs:/etc/letsencrypt
      - ./www:/www:ro
      - bunkerized-vol:/etc/nginx
    environment:
      - SERVER_NAME=
      - MULTISITE=yes
      #- AUTO_LETS_ENCRYPT=yes
    labels:
      - "bunkerized-nginx.AUTOCONF"
    networks:
      - services-net

  myautoconf:
    image: bunkerity/bunkerized-nginx-autoconf
    restart: always
    volumes_from:
      - mybunkerized
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - mybunkerized

volumes:
  bunkerized-vol:

networks:
  services-net:
    name: services-net
```

Run bunkerized and pwndoc

`docker-compose up -d`

`cd www/pwndoc.sorrow.local`

`docker-compose up --build`

If I comment mapping of port, i'm not able to reach Pwndoc. But with this, i'm able to reach service with ip and port, not only with SERVER_NAME.

Thank you to those who can help me.

**Comment by Sorrow81** [comment]
Work with pwndoc 0.5.3

```yaml
# docker-composer.autoconf.yaml

version: '3'

services:

  mybunker:
    image: bunkerity/bunkerweb:1.4.3
    ports:
      - 80:8080
      - 443:8443
    environment:
      - AUTOCONF_MODE=yes
      - MULTISITE=yes
      - SERVER_NAME=
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - USE_BAD_BEHAVIOR=no
    labels:
      - "bunkerweb.AUTOCONF"
    networks:
      - bw-autoconf
      - bw-services

  myautoconf:
    image: bunkerity/bunkerweb-autoconf:1.4.3
    volumes:
      - .:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - bw-autoconf

volumes:
  bw-data:

networks:
  bw-autoconf:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
```

```yaml
# docker-composer.pwndoc.yaml

version: '3'

services:

  mongo-pwndoc:
    image: mongo:4.2.15
    container_name: mongo-pwndoc
    volumes:
      - ./backend/mongo-data:/data/db
    restart: always
    environment:
      - MONGO_DB:pwndoc
    networks: 
      bw-services:
        aliases:
          - mongo-pwndoc

  pwndoc-backend:
    build: ./backend
    image: yeln4ts/pwndoc:backend
    container_name: pwndoc-backend
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
    depends_on:
      - mongo-pwndoc
    restart: always
    links:
      - mongo-pwndoc
    networks: 
      bw-services:
        aliases:
          - pwndoc-backend

  pwndoc-frontend:
    build: ./frontend
    image: yeln4ts/pwndoc:frontend
    container_name: pwndoc-frontend
    restart: always
    networks:
      bw-services:
        aliases:
          - pwndoc-frontend
    labels:
      - bunkerweb.SERVER_NAME=pwndoc.site.localhost
      - bunkerweb.USE_REVERSE_PROXY=yes
      - bunkerweb.REVERSE_PROXY_WS=yes
      - bunkerweb.REVERSE_PROXY_URL=/
      - bunkerweb.REVERSE_PROXY_HOST=https://pwndoc-frontend:8443
      - bunkerweb.USE_BAD_BEHAVIOR=yes
      - bunkerweb.LIMIT_REQ_URL_1=/socket.io
      - bunkerweb.LIMIT_REQ_RATE_1=10r/s    
     

volumes:
  mongo-data:

networks:
  bw-services:
    external:
      name: bw-services

  ```

You will also need to modify a pwndoc file to remove the port for the reverse proxy to work.

```js
// /pwndoc/frontend/src/boot/socketio.js

import io from 'socket.io-client'
import {Loading} from 'quasar'
import { $t } from '@/boot/i18n'

export default ({ Vue }) => {
    // var socket = io(`${window.location.protocol}//${window.location.hostname}:${process.env.API_PORT}`);
    var socket = io(`${window.location.protocol}//${window.location.hostname}`);

    socket.on('disconnect', (error) => {
        Loading.show({
            message: `<i class='material-icons'>wifi_off</i><br /><p>${$t('msg.wrongContactingBackend')}</p>`, 
            spinner: null, 
            backgroundColor: 'red-10', 
            customClass: 'loading-error',
            delay: 5000
        })
    })
    socket.on('connect', () => {    
        Loading.hide()
    })

    Vue.prototype.$socket = socket
}  
```
