### ISSUE TITLE
[BUG] I'm testing this in a new instance and seems like lets encrypt does not work?

### ISSUE THREAD

**Issue by sbe-arg** [bunkerity/bunkerweb#1179]
### What happened?

Fresh setup unable to lets encrypt as calls to /.well-known/acme-challenge/* are marked as BADBEHAVIOR. Disabling behavior allows lets encrypt to do its work.

this is odd
```
[INIT] letsencrypt:init() call successful : let's encrypt is not used
```

### How to reproduce?

```
name: 'bunkerweb'

services:

  bunkerweb:
    image: bunkerity/bunkerweb:1.5.6
    restart: unless-stopped
    ports:
      - 20080:8080
      - 20443:8443
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24 192.168.1.0/24
      - SERVER_NAME=site anothersite
      - MULTISITE=yes
      - USE_REVERSE_PROXY=yes # Will be applied to all server config
      - REVERSE_PROXY_URL=/ # Will be applied to all server config
      - site_AUTO_LETS_ENCRYPT=yes
      - site_EMAIL_LETS_ENCRYPT=email
      - site_REVERSE_PROXY_HOST=location
      - anothersite_AUTO_LETS_ENCRYPT=yes
      - anothersite_EMAIL_LETS_ENCRYPT=email
      - anothersite_REVERSE_PROXY_HOST=location
      - DENY_HTTP_STATUS=444 # over 403 default
      - USE_CLIENT_CACHE=no
      - MAX_CLIENT_SIZE=100m
      - LIMIT_REQ_RATE=50r/s
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.6
    restart: unless-stopped
    depends_on:
      - bunkerweb
      - bw-docker
    volumes:
      - bw-data:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```

### Relevant log output

```shell
- - [13/May/2024:05:27:39 +0000] "GET /.well-known/acme-challenge/id HTTP/1.1" 404 104970 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```
```


### BunkerWeb version

1.5.6

### What integration are you using?

Docker

### Linux distribution (if applicable)

_No response_

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
