### ISSUE TITLE
[BUG] Do I still need to add a crowdsec container? Why can't crowdsec start and there are no logs

### ISSUE THREAD

**Issue by andyoulovexy** [bunkerity/bunkerweb#1190]
### What happened?

Do I still need to add a crowdsec container? Why can't crowdsec start and there are no logs
![图片](https://github.com/bunkerity/bunkerweb/assets/38940994/79dc4493-da88-485c-ab4e-55cee3271512)

### How to reproduce?

Do I still need to add a crowdsec container? Why can't crowdsec start and there are no logs

### Configuration file(s) (yaml or .env)

```YAML
version: "3.5"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.5.7
    ports:
      - 80:8080
      - 443:8443
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - SERVER_NAME=www.andyou.com
      - MULTISITE=yes
      - DATABASE_URI=mariadb+pymysql://bunkerweb:xxxxx@xxxx:3306/db # Remember to set a stronger password for the database
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - USE_CLAMAV=yes
      - CLAMAV_HOST=clamav
      - USE_VIRUSTOTAL=yes
      - VIRUSTOTAL_API_KEY=xxxxx
      - AUTO_LETS_ENCRYPT=yes
      - USE_CROWDSEC=yes
      - CROWDSEC_API=http://crowdsec:8080
      - CROWDSEC_API_KEY=xxxxxx
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - www.andyou.com_USE_UI=yes
      - www.andyou.com_USE_REVERSE_PROXY=yes
      - www.andyou.com_REVERSE_PROXY_URL=/admin
      - www.andyou.com_REVERSE_PROXY_HOST=http://bw-ui:7000
      - www.andyou.com_INTERCEPTED_ERROR_CODES=400 404 405 413 429 500 501 502 503 504
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.7
    depends_on:
      - bunkerweb
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:xxxxx@xxxx:3306/db # Remember to set a stronger password for the database
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.0
    #image: andyou_crowdsec:v1
    volumes:
      - cs-data:/var/lib/crowdsec/data
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - bw-logs:/var/log:ro
    environment:
      - BOUNCER_KEY_bunkerweb=xxxxx
      - COLLECTIONS=crowdsecurity/nginx
    networks:
      - bw-universe

  syslog:
    image: balabit/syslog-ng:4.6.0
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - bw-logs:/var/log
    networks:
      bw-universe:
        ipv4_address: 10.20.30.254

  clamav:
    image: clamav/clamav:1.2
    volumes:
      - ./clamav-data:/var/lib/clamav
    networks:
      - bw-universe

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.5.7
    depends_on:
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:xxxx@xxxx:3306/db # Remember to set a stronger password for the database
      - DOCKER_HOST=tcp://bw-docker:2375
      - ADMIN_USERNAME=xxxxx
      - ADMIN_PASSWORD=xxxx # Remember to set a stronger password for the Abc1234% user
    networks:
      - bw-universe
      - bw-docker

  bw-db:
    image: mariadb:10.10
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxxx # Remember to set a stronger password for the database
    volumes:
      - bw-data:/var/lib/mysql
    networks:
      - bw-docker

volumes:
  bw-data:
  bw-logs:
  cs-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.xx.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```

### Relevant log output

```shell
no crowdsec logs
```

### BunkerWeb version

1.5.7

### What integration are you using?

Docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
