### ISSUE TITLE
[BUG] Lost API endpoint in nginx after a while

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#1277]
### What happened?

Afters some times i lost the api endpoint in nginx. Everything is working but the api endpoint is missing.

i check by `netstat` and the port related to the api is not listed.

i'v notice some lua errors but i don't know if there are related.

```
2024/06/13 13:39:44 [error] 1558#1558: *2183462 failed to run set_by_lua*: /usr/share/bunkerweb/deps/lib/lua/resty/lock.lua:154: API disabled in the context of set_by_lua*
stack traceback:
	[C]: in function 'sleep'
	/usr/share/bunkerweb/deps/lib/lua/resty/lock.lua:154: in function 'lock'
	/usr/share/bunkerweb/deps/lib/lua/resty/mlcache.lua:730: in function 'get'
	/usr/share/bunkerweb/lua/bunkerweb/cachestore.lua:107: in function 'get'
	set_by_lua(default-server-http/whitelist.conf:3):62: in main chunk, client: X.X.X.X, server: _, request: "GET / HTTP/1.1", host: "X.X.X.X"
```

### How to reproduce?

Juste run the containers and after a while bw-schduler can't reach the api endpoint and api port is not listen anymore by nginx

### Configuration file(s) (yaml or .env)

```YAML
`
  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.7
    container_name: bw-scheduler
    depends_on:
      - bw-docker-proxy
      - bw-db
      - bw-syslog-ng
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
    volumes:
      - ./nginx/config:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker-proxy:2375
      - LOG_LEVEL=notice
      - DATABASE_URI=mysql+pymysql://bunkerweb:XXXXX@bw-db:3306/db
    networks:
      - bw-universe
      - bw-docker
# Fix nginx running in host network
    extra_hosts:
      - "nginx:192.168.1.150"

  bw-db:
    image: mysql:latest
    container_name: bw-db
    user: "1024:101"
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXXXXXX
      - MYSQL_DATABASE=db
      - MYSQL_USER=bunkerweb
      - MYSQL_PASSWORD=XXXXXXXX
    command: --mysql-native-password=ON
    expose:
      - 3306
    volumes:
      - "./nginx/db:/var/lib/mysql"
    networks:
      - bw-universe

  nginx:
    image: bunkerity/bunkerweb:1.5.7
    container_name: nginx
    restart: always
    network_mode: "host"
    labels:
      - "bunkerweb.INSTANCE" # required for the scheduler to recognize the container
    volumes:
      # Set timezone
      - "/etc/TZ:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    # dropping all capabilities
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - authelia
      - bw-scheduler
      - bw-docker-proxy
      - bw-db
      - bw-syslog-ng
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
    environment:
      - EXTERNAL_PLUGIN_URLS=https://github.com/bunkerity/bunkerweb-plugins/archive/refs/tags/v1.5.zip
      - DATABASE_URI=mysql+pymysql://bunkerweb:XXXXXXX@bw-db:3306/db
      - MULTISITE=yes
      - LOG_LEVEL=notice
      - API_WHITELIST_IP=127.0.0.0/8 172.16.3.0/24 172.16.4.0/24
      - API_HTTP_PORT=5100
      - API_SERVER_NAME=nginx
      # Usefull for testing avoir letsencrypt blocked due to limits
      - USE_LETS_ENCRYPT_STAGING=no
      - AUTO_LETS_ENCRYPT=yes
      - EMAIL_LETS_ENCRYPT=admin@XXXXX
      - SERVER_NAME=XXXX
      - SERVE_FILES=no
      - REDIRECT_HTTP_TO_HTTPS=yes
      - DISABLE_DEFAULT_SERVER=yes
      - DNS_RESOLVERS=1.1.1.1 1.0.0.1
      - HTTP_PORT=10080
      - HTTPS_PORT=10443
      - HTTP2=yes
      - SSL_PROTOCOLS=TLSv1.2 TLSv1.3
      - USE_GZIP=yes
      - GZIP_COMP_LEVEL=5
      - GZIP_MIN_LENGTH=500
      - USE_BROTLI=yes
      - BROTLI_COMP_LEVEL=5
      - BROTLI_MIN_LENGTH=500

      - STRICT_TRANSPORT_SECURITY=max-age=31536000; includeSubDomains; preload

      # FIXME Too many FP
      - USE_BAD_BEHAVIOR=no
      - BAD_BEHAVIOR_STATUS_CODES=400 401 403 405 444 429


      - USE_DNSBL=yes

      # FIXME Tor exits nodes blocked by default !
      - USE_BLACKLIST=yes

      - USE_WHITELIST=yes
      - WHITELIST_IP=XXXX
      - GREYLIST_USER_AGENT=okhttp* WebDAV DAVx5* axios* sindresorhus* *ggpht.com GoogleImageProxy Python* aiohttp* Bitwarden_Mobile*

      - USE_REVERSE_PROXY=yes
      - USE_MODSECURITY=yes
      - USE_MODSECURITY_CRS=yes

      - USE_BUNKERNET=no
      - USE_API=no
      
      - USE_LIMIT_REQ=yes
      - LIMIT_REQ_RATE=200r/s

      - USE_LIMIT_CONN=yes
      - LIMIT_CONN_MAX_HTTP1=20
      - LIMIT_CONN_MAX_HTTP2=200
      
      - BLACKLIST_COUNTRY=CN RU
      
      - USE_OPEN_FILE_CACHE=yes
      - OPEN_FILE_CACHE=max=1000 inactive=60s
      - OPEN_FILE_CACHE_ERRORS=yes
      - OPEN_FILE_CACHE_MIN_USES=2
      - OPEN_FILE_CACHE_VALID=30s
      
        ### PLUGINS ###
        # FIXME TMP DISABLE
      - USE_CROWDSEC=no
      - CROWDSEC_API=http://127.0.0.1:48080
        # you need to generate it (see bouncer_key.sh)
      - CROWDSEC_API_KEY=XXXXXXXX
      - USE_VIRUSTOTAL=no
      - USE_DISCORD=no
      - USE_SLACK=no
      - USE_CLAMAV=no
      - USE_CORAZA=no
````
```


### Relevant log output

```shell
2024/06/13 13:39:44 [error] 1558#1558: *2183462 failed to run set_by_lua*: /usr/share/bunkerweb/deps/lib/lua/resty/lock.lua:154: API disabled in the context of set_by_lua*
stack traceback:
	[C]: in function 'sleep'
	/usr/share/bunkerweb/deps/lib/lua/resty/lock.lua:154: in function 'lock'
	/usr/share/bunkerweb/deps/lib/lua/resty/mlcache.lua:730: in function 'get'
	/usr/share/bunkerweb/lua/bunkerweb/cachestore.lua:107: in function 'get'
	set_by_lua(default-server-http/whitelist.conf:3):62: in main chunk, client: X.X.X.X, server: _, request: "GET / HTTP/1.1", host: "X.X.X.X"
```

```
[2024-06-14 20:34:21] - API - ❌ - Can't send API request to http://nginx:5100/cache : Request failed: HTTPConnectionPool(host='nginx', port=5100): Max retries exceeded with url: /cache (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff5a4132210>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-06-14 20:34:21] - SCHEDULER - ❌ - Error while sending /var/cache/bunkerweb folder
[2024-06-14 20:34:21] - SCHEDULER - ℹ️  - Reloading nginx ...
[2024-06-14 20:34:21] - API - ❌ - Can't send API request to http://nginx:5100/reload : Request failed: HTTPConnectionPool(host='nginx', port=5100): Max retries exceeded with url: /reload (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff5a4133980>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-06-14 20:34:21] - SCHEDULER - ❌ - Error while reloading nginx

```
```


### BunkerWeb version

1.5.7

### What integration are you using?

Docker

### Linux distribution (if applicable)

_No response_

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
