### ISSUE TITLE
[FEATURE] Add mysql 8.4 compatibility

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#1309]
### What's needed and why?

Backup configuration is not working with mysql 8.4
Mysql has removed the `--default-authentication-plugin` has been removed in mysql 8.4 and rename to --mysql-native-password=ON` but backup configuration is still not working even with that's option.

```
Failed to dump the database: mysqldump: Got error: 1045: "Plugin caching_sha2_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/caching_sha2_password.so: No such file or directory" when trying to connect
```

my mysql docker configuration is as follows (latest mysql 8.4)
```
  bw-db:
    image: mysql:latest
    container_name: bw-db
    user: "1024:101"
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXX
      - MYSQL_DATABASE=db
      - MYSQL_USER=bunkerweb
      - MYSQL_PASSWORD=XXXXX
    command: --mysql-native-password=ON
    expose:
      - 3306
    volumes:
      - "./nginx/db:/var/lib/mysql"
    networks:
      - bw-universe
```
This is happening since bunker web 1.5.4
It's just the dump command which get an issue, every other actions on database are working.

```
[2024-06-25 17:35:34 +0000] [CUSTOM-CERT] [176] [ℹ️ ] - ✅ Database connection established
[2024-06-25 17:35:34 +0000] [LETS-ENCRYPT.NEW] [187] [ℹ️ ] - ✅ Database connection established


Follow [https://discord.com/channels/854285298476646421/1255218557474836601](https://discord.com/channels/854285298476646421/1255218557474836601)

### Implementations ideas (optional)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
