### ISSUE TITLE
[HELP] using BunkerWeb via localhost custom port

### ISSUE THREAD

**Issue by spwoodcock** [bunkerity/bunkerweb#1366]
### What happened?

Hi there, I imagine this is a help request rather than a bug, as it's likely just my misconfiguration.

I would love to use bunkerweb for a few tools I maintain, replacing a custom Nginx image.

I need the setup to work both on a production domain, and on localhost during development, but have failed to set it up when running locally.

I can't seem to get my services to load when attempting to use http `localhost` as my domain, on a custom port number (`7050` instead of `80`).

When I try to load my service I just get a screen saying 'Generating Bunkerweb Config' that refreshes every few seconds:

![image](https://github.com/user-attachments/assets/ca510d3a-6359-430d-8976-3c8e92c079a8)

Is it possible to run bunkerweb on `localhost` or `xxx.localhost` domains?

### How to reproduce?

Running via Docker Compose, config attached.

### Configuration file(s) (yaml or .env)

```YAML
networks:
  local-net:
    name: local-net

services:
  proxy:
    image: "ghcr.io/bunkerity/bunkerweb:1.5.8"
    depends_on:
      api:
        condition: service_started
    environment:
      USE_REVERSE_PROXY: yes
      SERVER_NAME: api.localhost
      REVERSE_PROXY_HOST: http://api:8000
    ports:
      - ${DEV_PORT:-7050}:8080
    networks:
      - local-net
    restart: "unless-stopped"

  api:
    image: "jdkelley/simple-http-server:latest"
    networks:
      - local-net
    restart: "unless-stopped"
```

### Relevant log output

`docker compose logs proxy`:

```shell
proxy-1  | [2024-07-21 00:31:19] - ENTRYPOINT - ℹ️ - Starting BunkerWeb v1.5.8 ...
proxy-1  | [2024-07-21 00:31:19] - ENTRYPOINT - ℹ️ - Setup and check /data folder ...
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Generator started ...
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Settings : /usr/share/bunkerweb/settings.json
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Templates : /usr/share/bunkerweb/confs
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Core : /usr/share/bunkerweb/core
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Plugins : /etc/bunkerweb/plugins
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Pro plugins : /etc/bunkerweb/pro/plugins
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Output : /etc/nginx
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Target : /etc/nginx
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Variables : /tmp/variables.env
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Checking arguments ...
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Computing config ...
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Removing old files ...
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Rendering templates ...
proxy-1  | [2024-07-21 00:31:19 +0000] [GENERATOR] [15] [ℹ️ ] - Generator successfully executed !
proxy-1  | [2024-07-21 00:31:19] - ENTRYPOINT - ℹ️ - Starting nginx ...
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: ModSecurity-nginx v1.0.3 (rules loaded inline/local/remote: 0/0/0)
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] init phase started
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] deleting old keys from datastore ...
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] deleted old keys from datastore
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] saving plugins into datastore ...
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin whitelist v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin redirect v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin ui v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin bunkernet v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin metrics v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin jobs v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin customcert v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin authbasic v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin backup v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin country v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin db v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin php v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin dnsbl v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin clientcache v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin misc v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin headers v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin errors v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin reverseproxy v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin cors v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin brotli v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin gzip v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin antibot v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin redis v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin pro v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin letsencrypt v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin realip v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin sessions v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin inject v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin badbehavior v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin reversescan v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin modsecurity v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin blacklist v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin greylist v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin selfsigned v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] loaded plugin limit v1.0
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] saving variables into datastore ...
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] saved variables into datastore
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] saving plugins order into datastore ...
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase header : ["cors","misc","antibot","headers"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase timer : ["metrics"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase log_default : ["badbehavior","bunkernet","misc","metrics"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase log_stream : ["badbehavior","bunkernet"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase rewrite : {}
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase access : ["whitelist","letsencrypt","blacklist","greylist","country","dnsbl","bunkernet","reversescan","limit","misc","cors","antibot"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase content : ["antibot"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase set : ["sessions","whitelist","letsencrypt","customcert","selfsigned","ui"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase log : ["badbehavior","bunkernet","errors","metrics"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase ssl_certificate : ["customcert","letsencrypt","selfsigned"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase preread : ["whitelist","blacklist","greylist","country","dnsbl","reversescan"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase init : ["sessions","whitelist","blacklist","greylist","bunkernet","limit","selfsigned","customcert","headers","letsencrypt"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase init_worker : ["redis","bunkernet","dnsbl"]
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] plugins order for phase init_workers : {}
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] saved plugins order into datastore
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] calling init() methods of plugins ...
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] sessions:init() call successful : init not needed
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] whitelist:init() call successful : init not needed
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] blacklist:init() call successful : init not needed
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] greylist:init() call successful : init not needed
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] bunkernet:init() call successful : no service uses BunkerNet, skipping init
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] limit:init() call successful : no service uses limit for requests, skipping init
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] selfsigned:init() call successful : self signed is not used
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] customcert:init() call successful : custom cert is not used
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] headers:init() call successful : successfully loaded 1 custom headers
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] letsencrypt:init() call successful : let's encrypt is not used
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] called init() methods of plugins
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: [INIT] init phase ended
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: using the "epoll" event method
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: nginx/1.26.1
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: built by gcc 13.2.1 20231014 (Alpine 13.2.1_git20231014)
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: OS: Linux 5.15.146.1-microsoft-standard-WSL2
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: getrlimit(RLIMIT_NOFILE): 1048576:1048576
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker processes
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 56
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 57
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 58
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 59
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 60
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 61
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 62
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 63
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 64
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 65
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 66
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 67
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 68
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 69
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 70
proxy-1  | 2024/07/21 00:31:19 [notice] 52#52: start worker process 71
```

Headers:
![image](https://github.com/user-attachments/assets/d991e80f-7760-45e7-9b86-5b06d7b4cbed)

```
### BunkerWeb version

1.5.8

### What integration are you using?

Docker

### Linux distribution (if applicable)

Debian Bookworm

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @spwoodcock, looks like you forgot the [Scheduler](https://docs.bunkerweb.io/latest/integrations/#scheduler) container in your stack. 
Please check out our documentation: https://docs.bunkerweb.io/latest/integrations/#full-compose-file

**Comment by spwoodcock** [comment]
Oh nice, thanks @TheophileDiot !

I didn't understand the importance of the scheduler & thought it was optional 😅 
Now I see it actually generates the Nginx configs and sends them to the Bunkerweb container.

I was searching for any examples online of people using bunkerweb with a minimal config and found this https://computingforgeeks.com/run-nginx-in-docker-container-using-bunkerweb/ but I guess the info is incorrect there!

I tried a minimal config based on the docs you linked:

```yaml
networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker

services:
  bunkerweb:
    image: "ghcr.io/bunkerity/bunkerweb:1.5.9"
    depends_on:
      api:
        condition: service_started
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      USE_REVERSE_PROXY: yes
      SERVER_NAME: api.localhost
      REVERSE_PROXY_HOST: http://api:8000
    ports:
      - ${DEV_PORT:-7050}:8080
    networks:
      - bw-universe
      - bw-services
    restart: "unless-stopped"

  bw-scheduler:
    image: "ghcr.io/bunkerity/bunkerweb-scheduler:1.5.9"
    depends_on:
      - bunkerweb
      - bw-docker
    # volumes:
      # - bw-data:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: "docker.io/tecnativa/docker-socket-proxy:nightly"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

  api:
    image: "docker.io/jdkelley/simple-http-server:latest"
    networks:
      - bw-services
    restart: "unless-stopped"
```

This still doesn't work & I get the 'Generating Bunkerweb Config' screen as above.
More info is provided in the bw-scheduler logs this time though!

```
bw-scheduler-1  | [2024-07-22 17:46:19 +0000] [GENERATOR] [158] [ℹ️ ] - Computing config ...
bw-scheduler-1  | [2024-07-22 17:46:19 +0000] [GENERATOR] [158] [ℹ️ ] - Removing old files ...
bw-scheduler-1  | [2024-07-22 17:46:19 +0000] [GENERATOR] [158] [ℹ️ ] - Rendering templates ...
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [GENERATOR] [158] [ℹ️ ] - Generator successfully executed !
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [SCHEDULER] [22] [ℹ️ ] - Sending /etc/nginx folder ...
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [SCHEDULER] [22] [ℹ️ ] - Sending /var/cache/bunkerweb folder ...
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [API] [22] [❌] - Can't send API request to http://bunker-bunkerweb-1:5000/confs : Request failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [SCHEDULER] [22] [❌] - Sending nginx configs failed, configuration will not work as expected...
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [API] [22] [❌] - Can't send API request to http://bunker-bunkerweb-1:5000/cache : Request failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [SCHEDULER] [22] [❌] - Error while sending /var/cache/bunkerweb folder
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [API] [22] [❌] - Can't send API request to http://bunker-bunkerweb-1:5000/reload : Request failed: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [SCHEDULER] [22] [❌] - Error while reloading bunkerweb, failing over to last working configuration ...
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [SCHEDULER] [22] [❌] - No failover configuration found, ignoring failover ...
bw-scheduler-1  | [2024-07-22 17:46:20 +0000] [SCHEDULER] [22] [ℹ️ ] - Executing job scheduler ...
```

For some reason container networking fails between the bw-scheduler and bunkerweb container, or the service listening on bunkerweb port 5000 isn't running. 
The error `RemoteDisconnected('Remote end closed connection without response')` suggests that container networking is fine, but there is another source of the issue.

```
Docker version 26.1.3
Docker Compose version v2.27.0
```

**Comment by TheophileDiot** [comment]
Hi @spwoodcock, I would recommend using one of our working example. Before the 1.5.0 version the scheduler wasn’t detached into another container. 
The issue you have in your current stack is that the BunkerWeb container doesn’t allow the scheduler to send configuration as it is not part of a whitelisted network of the API. 
https://docs.bunkerweb.io/latest/settings/#global-settings

**Comment by spwoodcock** [comment]
My apologies! I missed the `API_WHITELIST_IP` var from the example.

Problem solved - thank you! 🎉

**Comment by spwoodcock** [comment]
Sorry to ping you again. I just thought I would post this in case it is useful for anyone.

I am testing bunkerweb and want to keep my resource footprint as small as possible.
The docker socket bind/proxy and scheduler are required to inject the nginx configs for bunkerweb.

However I tested simply shutting down the scheduler and proxy after one minute grace period for initialisation, and things seem to work fine:

```
volumes:
  nginx-configs:

networks:
  fmtm-net:
    name: fmtm-${GIT_BRANCH:-local}
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24

services:
  proxy:
    image: "ghcr.io/bunkerity/bunkerweb:1.5.9"
    depends_on:
      proxy-configs:
        condition: service_started
      api:
        condition: service_started
    volumes:
      # To save the generated configs
      - nginx-configs:/etc/nginx
    environment:
      API_WHITELIST_IP: 127.0.0.0/8 10.20.30.0/24
      MULTISITE: yes
      USE_REVERSE_PROXY: yes
      SERVER_NAME: fmtm.localhost api.fmtm.localhost odk.fmtm.localhost s3.fmtm.localhost
      fmtm.localhost_REVERSE_PROXY_HOST: http://ui:7051
      api.fmtm.localhost_REVERSE_PROXY_HOST: http://api:8000
      odk.fmtm.localhost_REVERSE_PROXY_HOST: http://central:8383
      s3.fmtm.localhost_REVERSE_PROXY_HOST: http://s3:9000
    ports:
      - ${FMTM_DEV_PORT:-7050}:8080
    networks:
      - fmtm-net
    restart: "unless-stopped"

  proxy-configs:
    image: "ghcr.io/bunkerity/bunkerweb-scheduler:1.5.9"
    depends_on:
      proxy-docker-sock:
        condition: service_started
    environment:
      - DOCKER_HOST=tcp://proxy-docker-sock:2375
    networks:
      - fmtm-net
    restart: "no"
    entrypoint: timeout 60 ./entrypoint.sh

  proxy-docker-sock:
    image: "docker.io/tecnativa/docker-socket-proxy:0.2.0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - fmtm-net
    restart: "no"
    command: timeout 60 haproxy -W -db -f /usr/local/etc/haproxy/haproxy.cfg

  api:
    ...
  ...other services
```
