### ISSUE TITLE
[FEATURE] Have a all-in-one image with the scheduler and BunkerWeb together

### ISSUE THREAD

**Issue by brandonkal** [bunkerity/bunkerweb#1423]
### What happened?

I did a quick test to evaluate this project. I spun it up with a docker compose file. I set the environment variables to disable http to https redirect. But all I got was a splash screen saying "generating config" that then redirects to https.

I have a few issues with this:
1. Users should not see a splash screen. Instead, I should be able to skip this whole "generating config step" and bake the config into the docker deployment image. I am evaluating for a scale-to-zero scenario so this extra latency is a negative
2. My config appears ineffective

### How to reproduce?

Just run this docker compose

### Configuration file(s) (yaml or .env)

```YAML
services:

  myapp:
    image: nginxdemos/nginx-hello
  bunkerweb:
    image: bunkerity/bunkerweb:1.5.9
    ports:
      - 80:8080
      - 443:8443
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      SERVER_NAME: ingress.example.com
      API_WHITELIST_IP: "0.0.0.0/0"
      USE_REVERSE_PROXY: yes
      AUTO_REDIRECT_HTTP_TO_HTTPS: no
      REDIRECT_HTTP_TO_HTTPS: no
      REVERSE_PROXY_URL: /
      REVERSE_PROXY_HOST: "http://myapp:8080"
      MULTISITE: no
```

### BunkerWeb version

1.5.9

### What integration are you using?

Docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fl0ppy-d1sk** [comment]
Hello @brandonkal, looks like the scheduler is missing from your compose file.

**Comment by brandonkal** [comment]
Yes, I don't want to run a separate scheduler. I am looking for single image solutions

**Comment by MrCybertux** [comment]
@brandonkal i do not know if bunkerweb is even able to run this way maybe have a look at bunkerized Nginx or if you want a simpler setup since all the bunkerized products are kind of advanced with the active Core Rule Set maybe try https://nginxproxymanager.com/

**Comment by TheophileDiot** [comment]
Hi, as of now no all-in-one images are available but maybe in the near future.

**Comment by spwoodcock** [comment]
For anyone looking for a way to simply run the main bunkweb container, without needing the scheduler, I have created a config for this:

```yaml
services:
  proxy:
    image: "ghcr.io/bunkerity/bunkerweb:1.5.9"
    environment:
      LOG_LEVEL: notice
      ...your config here
    ports:
      - 8080:8080
    networks:
      some-network:
    restart: "unless-stopped"

  proxy-config:
    image: "ghcr.io/bunkerity/bunkerweb-scheduler:1.5.9"
    depends_on:
      proxy-docker-sock:
        condition: service_started
    environment:
      - DOCKER_HOST=tcp://proxy-docker-sock:2375
    networks:
      some-network:
    restart: "no"
    entrypoint: timeout 120 ./entrypoint.sh

  proxy-docker-sock:
    image: "docker.io/tecnativa/docker-socket-proxy:0.2.0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      some-network:
    restart: "no"
    command: timeout 120 haproxy -W -db -f /usr/local/etc/haproxy/haproxy.cfg
```

This type of setup will simply:
  - Run the `proxy-config` (scheduler) service once, generating all the required configs for bunkerweb to run.
  - Shut down the scheduler and docker socket services.
  - Keep the main nginx bunkerweb service running in front of your apps.

+1 for an all-in-one solution that wouldn't require this config though 👍

**Comment by spwoodcock** [comment]
The above config does not work on v1.6.0 - the upgraded config is actually simpler:

```yaml
volumes:
  nginx-configs:

networks:
  some-network:

services:
  proxy:
    # Extend proxy-configs so environment var config is duplicated
    extends:
      service: proxy-config
    image: "ghcr.io/bunkerity/bunkerweb:1.5.9"
    volumes:
      - nginx-configs:/etc/nginx
    ports:
      - 8080:8080
    networks:
      some-network:
    restart: "unless-stopped"

  proxy-config:
    image: "ghcr.io/bunkerity/bunkerweb-scheduler:1.5.9"
    networks:
      some-network:
    restart: "no"
    entrypoint: timeout 120 ./entrypoint.sh
    # the environment variable config moved here
    environment:
      LOG_LEVEL: notice
      ...your config here

  # the socket proxy service is no longer required
```
