### ISSUE TITLE
[BUG] Docker-Compose setup

### ISSUE THREAD

**Issue by alwinhb** [bunkerity/bunkerweb#1466]
### What happened?

I am trying to setup the complete stack using docker-compose, I have added my compose.yaml

Kindly guide/suggest if my compose file is ok or needs to be updated.

### How to reproduce?

docker-compose up

### Configuration file(s) (yaml or .env)

```YAML
version: "3.5"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.5.9
    ports:
      - 80:8080
      - 443:8443
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - SERVER_NAME=www.example.com
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.9
    depends_on:
      - bunkerweb
      - bw-docker
    volumes:
      - bw-data:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```

### Relevant log output

```shell
bunker_waf-bw-scheduler-1  | Traceback (most recent call last):
bunker_waf-bw-scheduler-1  |   File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
bunker_waf-bw-scheduler-1  |     os.mkdir(self, mode)
bunker_waf-bw-scheduler-1  | FileExistsError: [Errno 17] File exists: '/var/cache/bunkerweb'
bunker_waf-bw-scheduler-1  | 
bunker_waf-bw-scheduler-1  | During handling of the above exception, another exception occurred:
bunker_waf-bw-scheduler-1  | 
bunker_waf-bw-scheduler-1  | Traceback (most recent call last):
bunker_waf-bw-scheduler-1  |   File "/usr/share/bunkerweb/scheduler/main.py", line 41, in <module>
bunker_waf-bw-scheduler-1  | 
bunker_waf-bw-scheduler-1  |     CACHE_PATH.mkdir(parents=True, exist_ok=True)
bunker_waf-bw-scheduler-1  |   File "/usr/local/lib/python3.12/pathlib.py", line 1320, in mkdir
bunker_waf-bw-scheduler-1  |     if not exist_ok or not self.is_dir():
bunker_waf-bw-scheduler-1  |                            ^^^^^^^^^^^^^
bunker_waf-bw-scheduler-1  |   File "/usr/local/lib/python3.12/pathlib.py", line 875, in is_dir
bunker_waf-bw-scheduler-1  |     return S_ISDIR(self.stat().st_mode)
bunker_waf-bw-scheduler-1  |                    ^^^^^^^^^^^
bunker_waf-bw-scheduler-1  |   File "/usr/local/lib/python3.12/pathlib.py", line 840, in stat
bunker_waf-bw-scheduler-1  |     return os.stat(self, follow_symlinks=follow_symlinks)
bunker_waf-bw-scheduler-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bunker_waf-bw-scheduler-1  | PermissionError: [Errno 13] Permission denied: '/var/cache/bunkerweb'
bunker_waf-bw-scheduler-1  | [2024-09-10 10:58:52] - ENTRYPOINT - ℹ️  - Scheduler stopped
```

### BunkerWeb version

1.5.9

### What integration are you using?

Docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
