### ISSUE TITLE
[FEATURE] K8S Use a ConfigMap for global config

### ISSUE THREAD

**Issue by schmittse** [bunkerity/bunkerweb#1658]
### What's needed and why?

Right now we have to set env variables on each deploy/daemonSet, a better approch would be to define a configMap and load the Env from this ConfigMap.

### Implementations ideas (optional)

From official documentation you can load env from a ConfigMap :
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: special-config
  restartPolicy: Never
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
