### ISSUE TITLE
[FEATURE] Bunkerweb access to additional nginx "listen" directives

### ISSUE THREAD

**Issue by CrustyAvocado** [bunkerity/bunkerweb#1659]
### What's needed and why?

I'd like bunkerweb to be able to add/remove additional "listen" directives to its nginx server for specific servers

For example in vanilla nginx I have every server configured to listen on 80 and 443, but some servers I need to listen on an additional dedicated HTTPS port (see example nginx config template below).

```
    server {
        listen *:80;
        listen [::]:80;
        listen *:443 ssl;
        listen [::]:443 ssl;
        listen *:32400 ssl;
        listen [::]:32400 ssl;

```

### Implementations ideas (optional)

```
services:
  bunkerweb:
    container_name: bunkerweb
    environment:
      - MULTISITE=yes
      - LISTEN_HTTP=yes
      - LISTEN_HTTPS=yes
      - LISTEN_STREAM=no
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - SERVER_NAME=plex.domain.com radarr.domain.com
      - plex.domain.com_REVERSE_PROXY_HOST=http://172.19.44.44:32400
      - plex.domain.com_HTTPS_PORT=32400      <--- THIS PLEASE
      - radarr.domain.com_REVERSE_PROXY_HOST=http://172.19.44.55:5055
    image: bunkerity/bunkerweb:latest

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
