### ISSUE TITLE
[BUG] Header settings like PERMISSIONS_POLICY or FEATURE_POLICY not taken into account

### ISSUE THREAD

**Issue by mariovitale1979** [bunkerity/bunkerweb#1767]
### What happened?

It's not possible to overwrite the PERMISSIONS_POLICY and/or FEATURE_POLICY settings . Problably same issue with tghe other HEADER setting options but not tested

### How to reproduce?

Using the config generator from Bunkerweb (https://config.bunkerweb.io/v1.5.11)  I generated a config to be used with docker compose. In my case I needed to change the PERMISSION_POLICY for fullscreen.
The generated PERMISSION_POLICY was:
 - www.example.com_PERMISSIONS_POLICY=accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(self), geolocation=(), gyroscope=(), hid=(), idle-detection=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), usb=(), web-share=(), xr-spatial-tracking=()
  

### Configuration file(s) (yaml or .env)

```YAML
version: '3.5'

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.5.12
    ports:
      - 80:8080
      - 443:8443
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - SERVER_NAME=www.example.com
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - www.example.com_PERMISSIONS_POLICY=accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(self), geolocation=(), gyroscope=(), hid=(), idle-detection=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), usb=(), web-share=(), xr-spatial-tracking=()
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.12
    depends_on:
      - bunkerweb
      - bw-docker
    volumes:
      - bw-data:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```

### Relevant log output

```shell
The change 'fullscreen=(self)' are not taken into account. 
1. The browser keeps returning the default headers 
2. When you login into the bunkerweb container and look at the file /etc/nginx/variables.env, you can also see there that the default PERMISSIONS_POLICY is still used
```

### BunkerWeb version

1.5.12

### What integration are you using?

Docker

### Linux distribution (if applicable)

ubuntu

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
