### ISSUE TITLE
[BUG] Not BunkerNet ID Instance

### ISSUE THREAD

**Issue by NagaDorset** [bunkerity/bunkerweb#1907]
### What happened?

Hello,
I installed and configured an instance of BunkerWeb (v1.6.0-rc1) with docker compose on my personal NAS. It works correctly.

I wanted to configure the BunkerNet plugin but I don't have the file /var/cache/bunkerweb/bunkernet/instance.id :(
The USE_BUNKERNET variable has the value "yes"

Do you know why?

### How to reproduce?

USE_BUNKERNET=yes

### Configuration file(s) (yaml or .env)

```YAML
x-env: &env
  DATABASE_URI: "mariadb+pymysql://bunkerweb:${DB_PASSWORD}@bw-db:3306/db"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.0-rc1
    container_name: bunkerweb
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp" # for QUIC
    environment:
      API_WHITELIST_IP: "127.0.0.0/24 10.20.30.0/24"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.0-rc1
    container_name: bw-scheduler
    depends_on:
      - bunkerweb
    volumes:
      - bw-data:/data
    environment:
      <<: *env
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: "www.example.com"
      MULTISITE: "yes"
      API_WHITELIST_IP: "127.0.0.0/24 10.20.30.0/24"
      SERVE_FILES: "no"
      AUTO_LETS_ENCRYPT: "yes"
      USE_CLIENT_CACHE: "yes"
      USE_GZIP: "yes"
      www.example.com_USE_TEMPLATE: "ui"
      www.example.com_USE_REVERSE_PROXY: "yes"
      www.example.com_REVERSE_PROXY_URL: "/"
      www.example.com_REVERSE_PROXY_HOST: "http://bw-ui:7000"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-db

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.6.0-rc1
    container_name: bw-ui
    environment:
      <<: *env
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    restart: "unless-stopped"
    volumes:
      - bw-data:/data
    ports:
      - 7000:7000
    networks:
      - bw-universe
      - bw-db

  bw-db:
    image: mariadb:11
    container_name: bw-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bw-db:/var/lib/mysql
    restart: "unless-stopped"
    networks:
      - bw-db

volumes:
  bw-data:
    name: bw-data
  bw-db:
    name: bw-db

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db
```

### Relevant log output

```shell
[2025-01-17 05:50:05 +0000] [BUNKERNET] [37] [ℹ️ ] - No BunkerNet ID found in db cache
[2025-01-17 05:50:05 +0000] [BUNKERNET] [37] [❌] - Not downloading BunkerNet data because instance is not registered
```

### BunkerWeb version

1.6.0-rc1

### What integration are you using?

Docker

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
