### ISSUE TITLE
[BUG] Block all traffic except local traffic not working. 

### ISSUE THREAD

**Issue by stoelpascal** [bunkerity/bunkerweb#191]
**Description**
First of all realy nice project, but I have problems with bloking trafic from all ip addresses except local trafic. 

Is this posible with these settings?
USE_BLACKLIST_IP=yes
BLACKLIST_IP_LIST=0.0.0.0/0
USE_WHITELIST_IP=yes
WHITELIST_IP_LIST=192.168.0.0/16

**How to reproduce**
Docker compose
```
version: '3'

services:

  mybunkerized:
    image: bunkerity/bunkerized-nginx
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - certs:/etc/letsencrypt
    environment:
      - SERVER_NAME=api.example.com nc.example.com
      - MULTISITE=yes
      - BAD_BEHAVIOR_BAN_TIME=600
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - USE_REVERSE_PROXY=yes
      - USE_BROTLI=yes
      - USE_CLIENT_CACHE=yes
      #app1.example.com
      - api.example.com_REVERSE_PROXY_URL=/
      - api.example.com_REVERSE_PROXY_HOST=http://192.168.2.10:32768
      #nc.example.com
      - nc.example.com_MAX_CLIENT_SIZE=100m
      - nc.example.com_ALLOWED_METHODS=GET|HEAD|POST|PUT|DELETE|CONNECT|OPTIONS|TRACE|PATCH|PROPFIND
      - nc.example.com_USE_MODSECURITY_CRS=no
      - nc.example.com_USE_LIMIT_REQ=no
      - nc.example.com_USE_BLACKLIST_IP=yes
      - nc.example.com_BLACKLIST_IP_LIST=0.0.0.0/0
      - nc.example.com_USE_WHITELIST_IP=yes
      - nc.example.com_WHITELIST_IP_LIST=192.168.0.0/16
      - nc.example.com_REVERSE_PROXY_URL=/
      - nc.example.com_REVERSE_PROXY_HOST=http://192.168.2.135
      
volumes:
  certs:
```

**Comment by fl0ppy-d1sk** [comment]
Hello @stoelpascal,

It should work that way. Do you have any logs or can you share what's not working as expected ? Please note that IPs inside the Whitelist won't be checked against security jobs. What about using iptables on the host instead ?

**Comment by fl0ppy-d1sk** [comment]
Hello @stoelpascal,

I can't reproduce your issue. Here is what I did.

docker-compose.yml used : 
```yaml
version: '3'

services:

  mybunkerized:
    image: bunkerity/bunkerized-nginx
    ports:
      - 80:8080
    environment:
      - SERVER_NAME=www.example.com
      - USE_BLACKLIST_IP=yes
      - BLACKLIST_IP_LIST=0.0.0.0/0
      - USE_WHITELIST_IP=yes
      - WHITELIST_IP_LIST=192.168.0.0/16
```

Execute bunkerized-nginx and wait until it's started : 
```shell
docker-compose down -v
docker-compose pull
docker-compose up -d
docker-compose logs -f
```

Doing a request from a whitelisted (inside 192.168.0.0/16 in this case) gives the following log : 
```log
2021/10/21 13:06:18 [notice] 101#101: *1 [WHITELIST] ip 192.168.32.1 is in whitelist, client: 192.168.32.1, server: www.example.com, request: "GET /something HTTP/1.1", host: "www.example.com"
```

And a request from any other IP will be blocked and we will see the following log : 
```log
2021/10/21 13:07:06 [warn] 101#101: *2 [BLACKLIST] ip 1.2.3.4 is in blacklist, client: 127.0.0.1, server: www.example.com, request: "GET /something HTTP/1.1", host: "www.example.com"
```

Can you share your bunkerized-nginx logs and maybe more info on what's not working as expected ?
