### ISSUE TITLE
[BUG] Let's Encrypt keeps attempting to renew certificates for domains that were deleted from Services

### ISSUE THREAD

**Issue by psychedelicu** [bunkerity/bunkerweb#1932]
### What happened?

Using BunkerWeb WebUI (v1.5.12) installed via Docker, Let's Encrypt keeps attempting to renew certificates for domains that were deleted from Services, causing log spam with errors like:
Failed to renew certificate <domain> with error: Some challenges have failed.

![Image](https://github.com/user-attachments/assets/7c16d9cc-49f5-42d7-800a-90d41c2b998e)

<img width="958" alt="Image" src="https://github.com/user-attachments/assets/66781b1a-2491-4e53-aa11-512994cdc401" />

### How to reproduce?

Steps to Reproduce:

Run BunkerWeb WebUI (v1.5.12) in Docker.
Delete a domain (e.g., test.example.com, test2.example.com) from Services.
Observe logs showing repeated attempts to renew certificates for the deleted domains.
Expected Behavior:
Deleted domains should no longer trigger certificate renewal attempts.

Actual Behavior:
BunkerWeb continues to attempt renewal for deleted domains.

Environment:
BunkerWeb WebUI: v1.5.12

### Configuration file(s) (yaml or .env)

```YAML
version: "3.5"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.5.12
    restart: unless-stopped

    ports:
      - 80:8080
      - 443:8443
    labels:
      - "bunkerweb.INSTANCE=yes"
    environment:
      - SERVER_NAME=example.com
      - MULTISITE=yes
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24 172.19.0.1/24
      - UI_HOST=http://bw-ui:7000 # Change it if needed

    volumes:
      - /etc/ssl/bunkerweb:/ssl:ro  # Mount SSL directory
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.12
    restart: unless-stopped
    volumes:
      - /etc/ssl/bunkerweb:/ssl:ro  # Mount SSL directory
    depends_on:
      - bunkerweb
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:pass!@bw-db:3306/db # Remember to set a stronger password for the database
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.5.12
    restart: unless-stopped
    depends_on:
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:pass!@bw-db:3306/db # Remember to set a stronger password for the database
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-db:
    image: mariadb:11.5.2
    restart: unless-stopped

    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=bunkerweb
      - MYSQL_PASSWORD=pass! # Remember to set a stronger password for the database
    volumes:
      - bw-data:/var/lib/mysql
    networks:
      - bw-docker

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```

### Relevant log output

```shell

```

### BunkerWeb version

1.5.12

### What integration are you using?

Docker

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
