### ISSUE TITLE
[BUG] Problems with new syslog container

### ISSUE THREAD

**Issue by SystemFuchs** [bunkerity/bunkerweb#2005]
### What happened?

Hi,

I've manually migrated my compose file from 1.5.12 to 1.6.0, got everything working & now tried to get logging working again. So I adapted your already new & fixed syslog configuration & getting the following error. 

The file ui.log isn't there because as per definition the file is tagged with bw-ui for syslog-ng?!

```
[2025-02-18 15:22:55] - ENTRYPOINT - ℹ️ - Web UI stopped with exit code 1
[2025-02-18 15:23:55] - ENTRYPOINT - ℹ️ - Starting the web UI v1.6.0 ...
[2025-02-18 15:23:55] - ENTRYPOINT - ℹ️ - Setup and check /data folder ...

Error: Error: '/var/log/bunkerweb/ui.log' isn't writable [PermissionError(13, 'Permission denied')]
```

```
➜  bw-logs ls -al
total 180
drwxrwxr-x 2 root       root         4096 Feb 18 16:27 .
drwxr-xr-x 3 root       root         4096 Feb 18 16:26 ..
-rwxrwx--- 1 messagebus messagebus 129109 Feb 18 16:33 bunkerweb.log
-rwxrwx--- 1 messagebus messagebus  31138 Feb 18 16:27 bw-scheduler.log
-rwxrwx--- 1 messagebus messagebus   4676 Feb 18 16:32 bw-ui.log
```

### How to reproduce?

Use the boilerplate code from latest documentation

### Configuration file(s) (yaml or .env)

```YAML
Docker compose.yml

version: "3.5"
services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.0
    container_name: bunkerweb
    restart: unless-stopped
    ports:
      - 80:8080/tcp
      - 443:8443/tcp
      - 443:8443/udp # for QUIC
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:******@bw-db:3306/db # Remember to set a stronger password for the database
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/2
    networks:
      - bw-universe
      - bw-services
    logging:
      driver: syslog
      options:
        tag: bunkerweb # This will be the tag used by syslog-ng to create the log file
        syslog-address: udp://10.20.30.254:514 # This is the syslog-ng container address
  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.0
    restart: unless-stopped
    depends_on:
      - bunkerweb
    environment:
      - BUNKERWEB_INSTANCES=bunkerweb
      - SERVER_NAME=bunkerweb.*******.de
      - MULTISITE=yes
      - AUTO_LETS_ENCRYPT=yes
      - EMAIL_LETS_ENCRYPT=********
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - bunkerweb.*******.de_USE_UI=yes
      - bunkerweb.*******.de_WHITELIST_IP=192.168.178.0/24
      - bunkerweb.*******.de_USE_REVERSE_PROXY=yes
      - bunkerweb.*******.de_REVERSE_PROXY_URL=/hackme
      - bunkerweb.*******.de_REVERSE_PROXY_HOST=http://bw-ui:7000
      - bunkerweb.*******.de_INTERCEPTED_ERROR_CODES=400 404 405 413 429 500
        501 502 503 504
      - bunkerweb.*******.de_MAX_CLIENT_SIZE=50m
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/2
      - DATABASE_URI=mariadb+pymysql://bunkerweb:***********@bw-db:3306/db # Remember to set a stronger password for the database
    volumes:
      - bw-scheduler:/data
    networks:
      - bw-universe
      - bw-db
    logging:
      driver: syslog
      options:
        tag: bw-scheduler # This will be the tag used by syslog-ng to create the log file
        syslog-address: udp://10.20.30.254:514 # This is the syslog-ng container address
  bw-ui:
    image: bunkerity/bunkerweb-ui:1.6.0
    restart: unless-stopped
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:**********@bw-db:3306/db # Remember to set a stronger password for the database
      - ADMIN_USERNAME=******
      - ADMIN_PASSWORD=********* # Remember to set a stronger password for the changeme user
    networks:
      - bw-universe
      - bw-db
    volumes:
      - ./bw-logs:/var/log/bunkerweb # This is the volume used to store the logs
    logging:
      driver: syslog
      options:
        tag: bw-ui # This will be the tag used by syslog-ng to create the log file
        syslog-address: udp://10.20.30.254:514 # This is the syslog-ng container address
  bw-db:
    image: mariadb:10.10
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=bunkerweb
      - MYSQL_PASSWORD=********* # Remember to set a stronger password for the database
    volumes:
      - bw-data:/var/lib/mysql
    networks:
      - bw-db
  bw-syslog:
    image: balabit/syslog-ng:4.8.0
    # image: lscr.io/linuxserver/syslog-ng:4.7.1-r1-ls116 # For aarch64 architecture
    cap_add:
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
      - DAC_READ_SEARCH
      - DAC_OVERRIDE
      - CHOWN
      - SYSLOG
    volumes:
      - ./bw-logs:/var/log/bunkerweb # This is the volume used to store the logs
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf # This is the syslog-ng configuration file
    networks:
      bw-universe:
        ipv4_address: 10.20.30.254 # Make sure to set the correct IP address
volumes:
  bw-data: null
  bw-scheduler: null
  bw-logs: null
networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db


syslog-ng.conf
@version: 4.7

# Source configuration to receive logs from Docker containers
source s_net {
  udp(
    ip("0.0.0.0")
  );
};

# Template to format log messages
template t_imp {
  template("$MSG\n");
  template_escape(no);
};

# Destination configuration to write logs to dynamically named files
destination d_dyna_file {
  file(
    "/var/log/bunkerweb/${PROGRAM}.log"
    template(t_imp)
    owner("101")
    group("101")
    dir_owner("root")
    dir_group("101")
    perm(0770)
    dir_perm(0770)
    create_dirs(yes)
  );
};

# Log path to direct logs to dynamically named files
log {
  source(s_net);
  destination(d_dyna_file);
};
```

### Relevant log output

```shell
[2025-02-18 15:22:55] - ENTRYPOINT - ℹ️ - Web UI stopped with exit code 1
[2025-02-18 15:23:55] - ENTRYPOINT - ℹ️ - Starting the web UI v1.6.0 ...
[2025-02-18 15:23:55] - ENTRYPOINT - ℹ️ - Setup and check /data folder ...

Error: Error: '/var/log/bunkerweb/ui.log' isn't writable [PermissionError(13, 'Permission denied')]
```

### BunkerWeb version

1.6.0

### What integration are you using?

Docker

### Linux distribution (if applicable)

Ubuntu 24.04

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
