### ISSUE TITLE
Reverse proxy auth do not request for a list of ip addresses

### ISSUE THREAD

**Issue by Striker72rus** [bunkerity/bunkerweb#2008]
Hi!
Please tell me, I'm setting it up
REVERSE_PROXY_AUTH
And I would like to make sure that for certain ip addresses it is not requested and immediately skipped further as if the field is empty.

Is there such a possibility?

**Comment by TheophileDiot** [comment]
Hi @Striker72rus, thank you for opening this issue.
Tell me if I understand it correctly but you're asking if there is a setting to skip the auth for specific IP address.
As of now there are no such feature available in BunkerWeb but feel free to open a [Feature Request](https://github.com/bunkerity/bunkerweb/issues/new?template=feature_request.yml).

Also maybe this can be done via the Auth service. For example you can tweak the [Access control](https://www.authelia.com/configuration/security/access-control/) with Authelia

**Comment by Striker72rus** [comment]
Yes, that's right, I want to avoid checking through authentic (which I have configured) for the ip list.

I used to have traefik, I set it up like this:

```
routers:
    monitoring-router-local:
        entryPoints:
          - https
        rule: (Host(`monitoring.xxx.com`) && ClientIP(`xxx.xxx.xxx.xxx`)) || (Host(`monitoring.xxx.com`) && ClientIP(`10.0.6.0/16`))
        service: monitoring
        tls:
          certResolver: letsEncrypt
    monitoring-router:
        entryPoints:
          - https
          - http
        rule: "Host(`monitoring.xxx.com`)"
        middlewares:
            - authentik
            - websocket-headers
        priority: 10
        tls:
          certResolver: letsEncrypt
```
