### ISSUE TITLE
[BUG] bw-ui Create a temporary volume

### ISSUE THREAD

**Issue by LiloBzH** [bunkerity/bunkerweb#2030]
### What happened?

Hi.

I'm testing version 1.6.0

I dont understand why but a temporary volume is created

```
  bw-ui:
    image: bunkerity/bunkerweb-ui:1.6.0
    environment:
      <<: *bw-env
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-db
```

```
HostnamePath:"/var/lib/docker/containers/ee0e6960faeb3eb757fb326bbf0a06cfedbf013662fb1ad83c508181a76ba4c3/hostname",
HostsPath:"/var/lib/docker/containers/ee0e6960faeb3eb757fb326bbf0a06cfedbf013662fb1ad83c508181a76ba4c3/hosts",
Id:"ee0e6960faeb3eb757fb326bbf0a06cfedbf013662fb1ad83c508181a76ba4c3",
Image:"sha256:a9420ab55e6d616525701f8bce8e25bcf85d0002e81c1f5242df59ebc28f9ca5",
LogPath:"/var/lib/docker/containers/ee0e6960faeb3eb757fb326bbf0a06cfedbf013662fb1ad83c508181a76ba4c3/ee0e6960faeb3eb757fb326bbf0a06cfedbf013662fb1ad83c508181a76ba4c3-json.log",
MountLabel:"",
Mounts:[
{
Destination:"/data",
Driver:"local",
Mode:"",
Name:"07c45216f5f947b04844b098ea9fada1f14878c3e5f77f40a6cc41d4ab0dad40",
Propagation:"",
RW:true,
Source:"/var/lib/docker/volumes/07c45216f5f947b04844b098ea9fada1f14878c3e5f77f40a6cc41d4ab0dad40/_data",
Type:"volume"
}
```

### How to reproduce?

Reboot Stack

### Configuration file(s) (yaml or .env)

```YAML
x-bw-env: &bw-env
  # We use an anchor to avoid repeating the same settings for both services
  API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24" # Make sure to set the correct IP range so the scheduler can send the configuration to the instance
  DATABASE_URI: "mariadb+pymysql://aaaaaaaaaaaaa:bbbbbbbbbbbbbb@bw-db:3306/db" # Remember to set a stronger password for the database

services:
  bunkerweb:
    # This is the name that will be used to identify the instance in the Scheduler
    image: bunkerity/bunkerweb:1.6.0
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp" # For QUIC / HTTP3 support
    environment:
      <<: *bw-env # We use the anchor to avoid repeating the same settings for all services
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.0
    environment:
      <<: *bw-env
      BUNKERWEB_INSTANCES: "bunkerweb" # Make sure to set the correct instance name
      SERVER_NAME: "bunkerweb.siteweb.com"
      MULTISITE: "yes"
      UI_HOST: "http://bw-ui:7000" # Change it if needed
      bunkerweb.siteweb.com_USE_TEMPLATE: "ui"
      bunkerweb.siteweb.com_USE_REVERSE_PROXY: "yes"
      bunkerweb.siteweb.com_REVERSE_PROXY_URL: "/admin" # Change it to a hard to guess URI
      bunkerweb.siteweb.com_REVERSE_PROXY_HOST: "http://bw-ui:7000"
    volumes:
      - bw-storage:/data # This is used to persist the cache and other data like the backups
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-db

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.6.0
    environment:
      <<: *bw-env
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-db

  bw-db:
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "aaaaaaaaaa"
      MYSQL_PASSWORD: "bbbbbbbbbbbbbbb" # Remember to set a stronger password for the database
    volumes:
      - bw-data:/var/lib/mysql
    restart: "unless-stopped"
    networks:
      - bw-db

volumes:
  bw-data:
  bw-storage:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24 # Make sure to set the correct IP range so the scheduler can send the configuration to the instance
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db
```

### Relevant log output

```shell

```

### BunkerWeb version

1.6.0

### What integration are you using?

Docker

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
