### ISSUE TITLE
[FEATURE] Path exclusions for captcha: let mobile apps bypass captcha (api)

### ISSUE THREAD

**Issue by signo1337** [bunkerity/bunkerweb#2076]
### What's needed and why?

I'd love to see an option to exclude specific paths from offering a captcha. I.e. mobile apps that connect via api typically don't present / relay the captcha. so it would be perfect if certain paths, e.g. /api, can be excluded from having to solve a captcha. that way, connection via browser is still protected from bots, whereas the mobile app continues to work.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @d4rkw1n9, thank you for opening this issue. I'll see what we can do to have some user friendly exclusion rules.

**Comment by TheophileDiot** [comment]
Hi @d4rkw1n9, I implemented the same system as for the blacklist ignore rules for the antibot. It will be available in the next minor release! 🥳

**Comment by MrCybertux** [comment]
@TheophileDiot I am running the 1.6.2-rc1 to test this feature.
I wanted to protect my login page only since the login generates an access token and without that there is no access to my ntfy.
The mobile application does not use the /login URI.
I get those errors:
```
bunkerweb-1  | ntfy.example.nl 146.70.0.XXX - user [03/May/2025:10:06:37 +0000] "GET /example_topic HTTP/1.1" 302 138 "-" "ntfy/1.16.0 (fdroid; Android 13; SDK 33)"
bunkerweb-1  | 2025/05/03 10:06:37 [warn] 229#229: *536 [UTILS] can't open session : missing session cookie, client: 146.70.0.XXX, server: ntfy.example.nl, request: "GET /challenge HTTP/1.1", host: "ntfy.example.nl"
bunkerweb-1  | 2025/05/03 10:06:37 [notice] 229#229: *536 [ACCESS] antibot returned status 0 : displaying challenge to client, client: 146.70.0.XXX, server: ntfy.example.nl, request: "GET /challenge HTTP/1.1", host: "ntfy.example.nl"
bunkerweb-1  | ntfy.example.nl 146.70.0.XXX - user [03/May/2025:10:06:37 +0000] "GET /challenge HTTP/1.1" 200 14962 "-" "ntfy/1.16.0 (fdroid; Android 13; SDK 33)"

```

but this according to my understanding should not happen I did the following antibot setup:

```
      - ntfy.example.nl_USE_ANTIBOT=javascript
      - ntfy.example.nl_ANTIBOT_IGNORE_URI="^(?!/login/?$).*"
```

Maybe you could share some more information on the workings of the new feature :-)

**Comment by TheophileDiot** [comment]
Hi @MrCybertux, you need to escape the `$` sign when using compose files: https://stackoverflow.com/a/40621373

**Comment by MrCybertux** [comment]
@TheophileDiot WOW you give answers on the weekend Thanks a lot!

Sorry my weekend is kind of full, so I was not able to test the solution until now.
As far as I can tell it works!
Also, I noticed the "" were causing problems.

**Comment by LeVraiRoiDHyrule** [comment]
Hello,

I am having what I think is the same problem with `can't open session : missing session cookie`. Currently on 1.6.2-rc2, and having the following error loop on some of my subdomains:
https://privatebin.net/?d1cc4a7c53de3987#32AKVk1gzLuoUh3yYcdfCq5or5eJePWtBcmLav2mphin

The error happens mostly on the subdomain that leads to my oid provider.

My setup for this service is the following:
```yaml
    labels:
      bunkerweb.SERVER_NAME: gotify.${DOMAIN}
      bunkerweb.USE_REVERSE_PROXY: yes
      bunkerweb.REVERSE_PROXY_URL: /
      bunkerweb.REVERSE_PROXY_HOST: http://gotify:80
      bunkerweb.ANTIBOT_IGNORE_URI: "^/version ^/application ^/message* ^/current/* ^/stream ^/static/* ^/client ^/plugin ^/users"
      bunkerweb.REVERSE_PROXY_WS: yes
      bunkerweb.LIMIT_REQ_RATE: 30r/s
      bunkerweb.ALLOWED_METHODS: "GET|POST|HEAD|DELETE"

      bunkerweb.REVERSE_PROXY_URL_2: "~ ^/(version|stream|application|message.*|current/.*)$"
      bunkerweb.REVERSE_PROXY_HOST_2: http://gotify:80
      bunkerweb.REVERSE_PROXY_AUTH_REQUEST_2:
      bunkerweb.REVERSE_PROXY_AUTH_REQUEST_SET_2:
      bunkerweb.REVERSE_PROXY_WS_2: yes
      <<: *authrequest
      bunkerweb.CUSTOM_CONF_MODSEC_gotify: |
        SecRuleRemoveById 920170
      bunkerweb.CUSTOM_CONF_MODSEC_2_gotify: |
        SecRuleRemoveById 920170
```
```yaml
x-authrequest: &authrequest
  bunkerweb.REVERSE_PROXY_AUTH_REQUEST: /outpost.goauthentik.io/auth/nginx
  #bunkerweb.REVERSE_PROXY_AUTH_REQUEST_SIGNIN_URL: '@goauthentik_proxy_signin'
  bunkerweb.REVERSE_PROXY_AUTH_REQUEST_SET: $$auth_cookie $$upstream_http_set_cookie;$$authentik_username $$upstream_http_x_authentik_username;$$authentik_groups $$upstream_http_x_authentik_groups;$$authentik_entitlements $$upstream_http_x_authentik_entitlements;$$authentik_email $$upstream_http_x_authentik_email;$$authentik_name $$upstream_http_x_authentik_name;$$authentik_uid $$upstream_http_x_authentik_uid
  bunkerweb.REVERSE_PROXY_HEADERS: X-authentik-username $$authentik_username;X-authentik-groups $$authentik_groups;X-authentik-entitlements $$authentik_entitlements;X-authentik-email $$authentik_email;X-authentik-name $$authentik_name;X-authentik-uid $$authentik_uid
  bunkerweb.REVERSE_PROXY_HEADERS_CLIENT: Set-Cookie $$auth_cookie
  bunkerweb.ERRORS: '401=@goauthentik_proxy_signin'
  bunkerweb.REVERSE_PROXY_INTERCEPT_ERRORS: no

  bunkerweb.CUSTOM_CONF_SERVER_HTTP_authrequestlocations: |
    location /outpost.goauthentik.io {
        proxy_pass              http://authentik-server:9000/outpost.goauthentik.io;

        proxy_set_header        Host $$host;

        proxy_set_header        X-Original-URL $$scheme://$$http_host$$request_uri;
        add_header              Set-Cookie $$auth_cookie;
        auth_request_set        $$auth_cookie $$upstream_http_set_cookie;
        proxy_pass_request_body off;
        proxy_set_header        Content-Length "";
    }
    location @goauthentik_proxy_signin {
        internal;
        add_header Set-Cookie $$auth_cookie;
        return 302 /outpost.goauthentik.io/start?rd=$$scheme://$$http_host$$request_uri;
    }
```
