### ISSUE TITLE
[BUG] SoGo and mailcow behind bunkerweb ends with 500 Error

### ISSUE THREAD

**Issue by zenfokus** [bunkerity/bunkerweb#2087]
### What happened?

Hello dear team,

First of all, many thanks for your great work.

I have switched Bunkerweb before Sogo with Mailcow and have noticed that a 500 error is issued after logging into the mailbox.

Unfortunately, the logs don't tell me enough to be able to work with it.

I suspect that an adjustment to Bunkerweb's reverse proxy is necessary. 

My configuration: 

traefik -> bunkerweb -> nginx -> mailcow-nginx ends in 500 error
traefik -> nginx -> mailcow-nginx works without problems

The admin UI of Mailcow works without problems. Only SoGo ends in a 500 error.

Perhaps someone has an idea.

Best regards
Mathias

![Image](https://github.com/user-attachments/assets/ff404544-a36b-4518-b522-f2d5690574db)

### How to reproduce?

I have not made any special adjustments. 

Mailcow runs as standard. Only the nginx is an additional container.

### Configuration file(s) (yaml or .env)

```YAML
services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.0
    container_name: ${APP_NAME}-bunkerweb
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=traefik-${APP_NAME}"

    # Routers
    - "traefik.http.routers.${APP_NAME}-web.middlewares=${APP_NAME}-redirect-to-https"
    - "traefik.http.routers.${APP_NAME}-web-secure.middlewares=gzip-compressing,${APP_NAME}-sts-headers,${APP_NAME}-secure-headers,${APP_NAME}-crowdsec-waf"

    # HTTP Router
    - "traefik.http.middlewares.${APP_NAME}-redirect-to-https.redirectscheme.scheme=https"
    - "traefik.http.middlewares.${APP_NAME}-redirect-to-https.redirectscheme.permanent=true"

    - "traefik.http.routers.${APP_NAME}-web.rule=Host(`mail.example.com`) || Host(`webmail.example.com`)"
    - "traefik.http.routers.${APP_NAME}-web.entrypoints=web"

    # HTTPS Router
    - "traefik.http.routers.${APP_NAME}-web-secure.rule=Host(`mail.example.com`) || Host(`webmail.example.com`)"
    - "traefik.http.routers.${APP_NAME}-web-secure.entrypoints=websecure"
    - "traefik.http.routers.${APP_NAME}-web-secure.tls=true"
    - "traefik.http.routers.${APP_NAME}-web-secure.tls.certresolver=certresolv"

    - "traefik.http.services.${APP_NAME}-web-secure.loadbalancer.server.scheme=https"
    - "traefik.http.services.${APP_NAME}-web-secure.loadbalancer.server.port=8443"

    # enable gzip compression
    - "traefik.http.middlewares.gzip-compressing.compress=true"

    # Security Headers Middleware
    - "traefik.http.middlewares.${APP_NAME}-sts-headers.headers.stsSeconds=31536000"
    - "traefik.http.middlewares.${APP_NAME}-sts-headers.headers.stsIncludeSubdomains=true"
    - "traefik.http.middlewares.${APP_NAME}-sts-headers.headers.stsPreload=true"
    - "traefik.http.middlewares.${APP_NAME}-secure-headers.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
    - "traefik.http.middlewares.${APP_NAME}-secure-headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
    - "traefik.http.middlewares.${APP_NAME}-secure-headers.headers.customResponseHeaders.Referrer-Policy=no-referrer"
    - "traefik.http.middlewares.${APP_NAME}-secure-headers.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"
    - "traefik.http.middlewares.${APP_NAME}-secure-headers.headers.customResponseHeaders.Strict-Transport-Security=max-age=63072000; includeSubDomains; preload"

    # crowdsec-bouncer
    - "traefik.http.middlewares.${APP_NAME}-crowdsec-waf.plugin.crowdsec-bouncer.enabled=true"
    - "traefik.http.middlewares.${APP_NAME}-crowdsec-waf.plugin.crowdsec-bouncer.crowdseclapikey=<token>"
    expose:
    - "8080"
    - "8443"
    environment:
    - API_WHITELIST_IP=127.0.0.0/8 172.16.0.0/12 10.20.20.0/24
    volumes:
      - ${DOCKER_VOL_PATH}/${APP_NAME}/${BW_WEB_LOG_VOLUME}:/var/log/bunkerweb
    depends_on:
    - web
    restart: always
    networks:
    - traefik
    - bw-universe
    - bw-services
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  web:
    image: lscr.io/linuxserver/nginx:latest
    container_name: ${APP_NAME}-web
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Berlin
    volumes:
    - /var/lib/docker/volumes/${APP_NAME}/_data/nginx/config:/config
    - /var/lib/docker/volumes/default-certs/_data/:/default-certs/
    networks:
    - traefik
    - mailcow-network
    - bw-services
    expose:
    - "14443"
    restart: always

networks:
  traefik:
    external: true
    name: traefik-mailcow-nginx
  mailcow-network:
    external:
      name: mailcowdockerized_mailcow-network
  bw-services:
    external: true
    name: bw-services
  bw-universe:
    external: true
    name: bw-universe



nginx config:

server {
    listen 14443 ssl;
    server_name webmail.example.com;

    ssl_certificate     /default-certs/nginx-default.crt;
    ssl_certificate_key /default-certs/nginx-default.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';

    location / {
        rewrite ^/$ /SOGo;
        proxy_pass http://mailcowdockerized-nginx-mailcow-1:15080;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 0;

        proxy_buffer_size 128k;
        proxy_buffers 64 512k;
        proxy_busy_buffers_size 512k;
    }
}
```

### Relevant log output

```shell
Bunkerweb Log:

example.com 80.249.116.46 - - [13/Mar/2025:12:36:02 +0000] "GET /SOGo/so/email@example.com/Calendar/alarmslist?browserTime=1741869362 HTTP/2.0" 500 87132 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0"
example.com 80.249.116.46 - - [13/Mar/2025:12:36:02 +0000] "GET /SOGo/so/email@example.com/Mail/0/view HTTP/2.0" 500 87132 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0"
example.com 80.249.116.46 - - [13/Mar/2025:12:36:02 +0000] "POST /SOGo/so/email@example.com/Mail/0/folderINBOX/changes HTTP/2.0" 500 87132 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0"

Sogo Logs:

Mar 13 13:45:51 8f7606c946cf sogod [73]: 80.249.116.46 "GET /SOGo/so/email@example.com/Calendar/alarmslist?browserTime=1741869952 HTTP/1.0" 500 36/0 0.009 - - 0 - 13
Mar 13 13:45:51 8f7606c946cf sogod [75]: 80.249.116.46 "POST /SOGo/so/email@example.com/Mail/0/folderINBOX/changes HTTP/1.0" 500 36/126 0.141 - - 0 - 13
Mar 13 13:45:51 8f7606c946cf sogod [77]: 80.249.116.46 "GET /SOGo/so/email@example.com/Mail/0/view HTTP/1.0" 500 36/0 0.149 - - 0 - 13
```

### BunkerWeb version

1.6.0

### What integration are you using?

Docker

### Linux distribution (if applicable)

Ubuntu 24.04

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
