### ISSUE TITLE
[BUG] OVH Kubernetes - Ingresses won't use the LoadBalancer

### ISSUE THREAD

**Issue by SebLecpac** [bunkerity/bunkerweb#2089]
### What happened?

I followed the guide on https://docs.bunkerweb.io/latest/integrations/#kubernetes and used the automatic install using helm chart to deploy a default version of bunkerweb on an OVH Managed Kubernetes Cluster.
It created the deployments, Datasets and other ressources accordingly to what was supposed to happen.
The service bunkerweb-external is created as a LoadBalancer and has an IP associated

However, when an ingress uses the ingressClassName: bunkerweb (that i also set in the controller as a value) the ingress never get the LoadBalancer ip and never become accessible.
When i tried to deploy a classic nginx ingress controller and use the same ingress with ingressClassName set to nginx the resolution and the access worked perfectly.

### How to reproduce?

Deploy bunkerweb on an OVH Managed Kubernetes Cluster using the helm chart on the github and try to create an ingress that uses the ingressClassName: bunkerweb.

### Configuration file(s) (yaml or .env)

```YAML
Here are the values that i use : 

imagePullSecrets:
  - name: regcred
nameOverride: "bunkerweb"
namespaceOverride: "bunkerweb"
fullnameOverride: "bunkerweb"
nodeSelector: {}
settings:
  kubernetes:
    ingressClass: "bunkerweb"
    domainName: "cluster.local"
  misc:
    databaseUri: "mariadb://bunkerweb:changeme@mariadb-bunkerweb.bunkerweb.svc.cluster.local:3306/bunkerweb"
    dnsResolvers: "kube-dns.kube-system.svc.cluster.local"
    apiWhitelistIp: "127.0.0.0/8 10.0.0.0/8"
  redis:
    useRedis: "yes"
    redisHost: "redis.bunkerweb.svc.cluster.local"
    redisUsername: "bunkerweb"
    redisPassword: "changeme"
  ui:
    ingress:
      enabled: true
      className: "bunkerweb"  # Set the ingress class to bunkerweb
      serverName: "bunkerweb-ui.cluster.local"
      serverPath: "/"
      tlsSecretName: "bunkerweb-ui-tls"
    adminUsername: "bunkerweb-ui-admin"
    adminPassword: "thJZ%dB^!5UhevG%2Yaw*Mzbw"
    flaskSecret: "flasksecret"
    totpSecrets: "totpsecrets"
service:
  enabled: true
  type: LoadBalancer  # Change service type to LoadBalancer
  annotations: 
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
    loadbalancer.openstack.org/proxy-protocol: "v2"
bunkerweb:
  repository: bunkerity/bunkerweb
  pullPolicy: Always
  tag: "1.6.0"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  podLabels:
    app: bunkerweb
  securityContext:
    runAsUser: 101
    runAsGroup: 101
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  extraEnvs:
    - name: BUNKERWEB_ENV
      value: "production"
    - name: USE_REAL_IP
      value: "yes"
    - name: USE_PROXY_PROTOCOL
      value: "yes"
    - name: REAL_IP_HEADER
      value: "proxy_protocol"
    - name: REAL_IP_FROM
      value: "10.0.0.0/8 192.168.0.0/16 172.16.0.0/12"
  livenessProbe:
    exec:
      command:
        - /usr/share/bunkerweb/helpers/healthcheck.sh
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
  readinessProbe:
    exec:
      command:
        - /usr/share/bunkerweb/helpers/healthcheck.sh
    initialDelaySeconds: 30
    periodSeconds: 1
    timeoutSeconds: 1
    failureThreshold: 3
scheduler:
  repository: bunkerity/bunkerweb-scheduler
  pullPolicy: Always
  tag: "1.6.0"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  podLabels:
    app: bunkerweb-scheduler
  securityContext:
    runAsUser: 101
    runAsGroup: 101
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  extraEnvs:
    - name: BUNKERWEB_ENV
      value: "production"
controller:
  repository: bunkerity/bunkerweb-autoconf
  pullPolicy: Always
  tag: "1.6.0"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  podLabels:
    app: bunkerweb-controller
  securityContext:
    runAsUser: 101
    runAsGroup: 101
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  extraEnvs:
    - name: BUNKERWEB_ENV
      value: "production"
ui:
  enabled: true
  repository: bunkerity/bunkerweb-ui
  pullPolicy: Always
  tag: "1.6.0"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  podLabels:
    app: bunkerweb-ui
  securityContext:
    runAsUser: 101
    runAsGroup: 101
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  extraEnvs:
    - name: BUNKERWEB_ENV
      value: "production"
mariadb:
  enabled: true
  persistence:
    size: 5Gi
    storageClass: ""
  config:
    database: "db"
    user: "bunkerweb"
    password: "changeme"
redis:
  enabled: true
  config:
    password: "changeme"
ingressClass:
  enabled: true
  name: "bunkerweb"
  controller: "bunkerweb.io/ingress-controller"
```

### Relevant log output

```shell

```

### BunkerWeb version

1.6.0

### What integration are you using?

Kubernetes

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by fl0ppy-d1sk** [comment]
Hi @SebLecpac,

The Ingress doesn't get the IP address of the LB in the metadata but still did you try to access the web service ?

**Comment by fl0ppy-d1sk** [comment]
Do you have any logs inside the controller pod ?

**Comment by fl0ppy-d1sk** [comment]
Also, can you access the web UI or not all ?

**Comment by SebLecpac** [comment]
This is the additionnal info i got : 
After testing it occured that i have a response in http but not in https 

on http i get : Error 400

on https i get : Connection Refused

I have success logs in the controller for the confs : 
[2025-03-14 13:30:41 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Successfully deployed new configuration 🚀
[2025-03-14 13:30:43 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:30:44 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:30:46 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:30:48 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:30:51 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:30:53 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:30:55 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Caught kubernetes event (service), deploying new configuration ...
[2025-03-14 13:30:55 +0000] [CONFIG] [1] [ℹ️ ] - Successfully saved new configuration 🚀
[2025-03-14 13:30:55 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Successfully deployed new configuration 🚀
[2025-03-14 13:31:17 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Caught kubernetes event (service), deploying new configuration ...
[2025-03-14 13:31:17 +0000] [CONFIG] [1] [ℹ️ ] - Successfully saved new configuration 🚀
[2025-03-14 13:31:17 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Successfully deployed new configuration 🚀
[2025-03-14 13:31:22 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:31:24 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:31:26 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:31:29 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:31:31 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:31:33 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:31:34 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Scheduler is already applying a configuration, retrying in 1 second ...
[2025-03-14 13:31:36 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Caught kubernetes event (pod), deploying new configuration ...
[2025-03-14 13:31:36 +0000] [CONFIG] [1] [ℹ️ ] - Successfully saved new configuration 🚀
[2025-03-14 13:31:36 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Successfully deployed new configuration 🚀
[2025-03-14 13:31:55 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Caught kubernetes event (pod), deploying new configuration ...
[2025-03-14 13:31:55 +0000] [CONFIG] [1] [ℹ️ ] - Successfully saved new configuration 🚀
[2025-03-14 13:31:55 +0000] [KUBERNETES-CONTROLLER] [1] [ℹ️ ] - Successfully deployed new configuration 🚀

In my daemon sets pods i got errors like those : 
_ 192.168.3.24 - - [14/Mar/2025:13:37:58 +0000] "\x00" 400 86965 "-" "-"
_ 192.168.3.24 - - [14/Mar/2025:13:38:01 +0000] "\x00" 400 86965 "-" "-"
_ 192.168.3.24 - - [14/Mar/2025:13:38:07 +0000] "\x00" 400 86965 "-" "-"
_ 192.168.3.24 - - [14/Mar/2025:13:38:10 +0000] "\x00" 400 86965 "-" "-"
_ 192.168.3.24 - - [14/Mar/2025:13:38:16 +0000] "\x00" 400 86965 "-" "-"
_ 192.168.3.24 - - [14/Mar/2025:13:38:19 +0000] "\x00" 400 86965 "-" "-"

When i check on my LoadBalancer logs i can see the connections : 
14/03/2025 14:39:39 | INFO | 11.11.11.11 1845
14/03/2025 14:39:40 | INFO | 11.11.11.11 1749
14/03/2025 14:39:41 | INFO | 11.11.11.11 1845

My loadbalancer protocol is set to proxyV2

I can access the webui through a local port forwarding and i can see there my services that are well detected and configured.
I also see the 400 errors for the ip address 192.168.3.24 that keeps failing

**Comment by fl0ppy-d1sk** [comment]
Can you please try to add the following extraEnvs on both the scheduler and BunkerWeb : 
```yaml
    - name: USE_REAL_IP
      value: "yes"
    - name: USE_PROXY_PROTOCOL
      value: "yes"
    - name: REAL_IP_HEADER
      value: "proxy_protocol"
    - name: REAL_IP_FROM
      value: "10.0.0.0/8 192.168.0.0/16 172.16.0.0/12"
```
