### ISSUE TITLE
[FEATURE] Expose multiple HTTP/S Ports

### ISSUE THREAD

**Issue by NoSpread** [bunkerity/bunkerweb#216]
**What's needed and why ?**
Unfortunately, due to the historical nature of the project, I cannot share all endpoints on port 80. This is also not possible under another sub-domain. So is it possible to also assign a dedicated port on a host to an endpoint?

So than for example you can customize the environment variables like this:

```yml
version: "3.9"
services:
  web:
 ...
    labels:
      bunkerized-nginx.USE_REVERSE_PROXY: "yes"
      bunkerized-nginx.SERVER_NAME_1: "web.example.com"
      bunkerized-nginx.REVERSE_PROXY_URL_1: "/"
      bunkerized-nginx.REVERSE_PROXY_HOST_1: "http://web:8080"
      bunkerized-nginx.HTTPS_PORT_2: 1234
      bunkerized-nginx.SERVER_NAME_2: "api.example.com"
      bunkerized-nginx.REVERSE_PROXY_URL_2: "/"
      bunkerized-nginx.REVERSE_PROXY_HOST_2: "http://web:8081"
...
```

**Implementations ideas (optional)**
This should be possible by simply creating another server block in the nginx config, and then assigning it to the 2nd endpoint. The implementation should work similar to the multiple reverse proxy configurations.
