### ISSUE TITLE
[BUG] Using variable in proxy_pass directive has side effects

### ISSUE THREAD

**Issue by quentinfougereau** [bunkerity/bunkerweb#218]
**Description**
I have an application behind bunkerized-nginx as a reverse-proxy. 
When I made requests to the reverse-proxy, the requests sent to the proxied server are always the same.

***Expected behavior***
The request `GET /foo/dir/` on the reverse-proxy should result in the following request on the proxied server : `GET /bar/dir`

***Current bug***
But the request `GET /foo/dir/` on the reverse-proxy become `GET /bar` on the proxied server

The bug is present since version 1.3.0 with the use of `$backend` variable in the `proxy_pass` directive.

On the [nginx website](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass), it says : 

> In some cases, the part of a request URI to be replaced cannot be determined: 
>    * When variables are used in proxy_pass:
> 
>     location /name/ {
>         proxy_pass http://127.0.0.1$request_uri;
>     }
> 
> In this case, if URI is specified in the directive, it is passed to the server as is, replacing the original request URI. 

**How to reproduce**
I used the following docker-compose file : 
```
version: '3'

services:
  app:
    image: nginx:latest

  bunkerized-nginx:
    image: bunkerity/bunkerized-nginx:1.3.0
    ports:
      - 80:8080
      - 443:8443
    environment:
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/foo
      - REVERSE_PROXY_HOST=http://app/bar
      - SERVE_FILES=no
      - USE_BAD_BEHAVIOR=no
    depends_on:
      - app
```

Then I requested the following URL `http://localhost/foo/dir/`. 

**Logs**
docker-compose logs

```
bunkerized-nginx_1  | localhost 172.25.0.1 - - [17/Dec/2021:09:07:31 +0000] "GET /foo/dir/ HTTP/1.1" 404 153 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"

app_1               | 172.25.0.3 - - [17/Dec/2021:09:07:31 +0000] "GET /bar HTTP/1.0" 404 153 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0" "172.25.0.1"
```
