### ISSUE TITLE
[BUG] Upstream address, when using reverse proxy, always resolved to ip address

### ISSUE THREAD

**Issue by jkunnen-structurizit** [bunkerity/bunkerweb#219]
**Description**
We want to setup a REVERSE PROXY configuration towards a backend server on which multiple applications are running.
So in short a multi site config. But it seems the upstream is always resolved into ip address for the destination. We want to keep the domain names for the backed destinations.

**How to reproduce**
```
Our yml docker compose file
version: '3'
services:
  mybunkerized:
    image: bunkerity/bunkerized-nginx
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./www:/www:ro
      - ./certs:/certs
    environment:
      - USE_REMOTE_API=no
      - SERVER_NAME=app1.domain.com app2.domain.com
      - DISABLE_DEFAULT_SERVER=yes
      - MULTISITE=yes
      - COOKIE_AUTO_SECURE_FLAG=yes
      - DNS_RESOLVERS=8.8.8.8 8.8.4.4
      - USE_CUSTOM_HTTPS=yes
      - CUSTOM_HTTPS_CERT=/certs/app.tld.chained.crt
      - CUSTOM_HTTPS_KEY=/certs/app.tld.key
      - app1.domain.com_USE_REVERSE_PROXY=yes
      - app1.domain.com_REVERSE_PROXY_URL=/
      - app1.domain.com_REVERSE_PROXY_HOST=https://app1.domain.com
      - app2.domain.com_USE_REVERSE_PROXY=yes
      - app2.domain.com_REVERSE_PROXY_URL=/
      - app2.domain.com_REVERSE_PROXY_HOST=https://app2.domain.com
 
```

After the host is started, we get the logs below. Meaning the destination backend host is immediately resolved to an upstream ip address. 
How can we avoid this? Because now the backend destination does not know which application to serve.

**Logs**
2021/12/20 20:12:49 [error] 189#189: *14 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: 212.x.x.x, server: app1.domain.com, request: "GET / HTTP/2.0", upstream: "https://x.x.x.154:443/", host: "app.domain.com"
