### ISSUE TITLE
[BUG] IP range in API_WHITELIST_IP ignored

### ISSUE THREAD

**Issue by axeleroy** [bunkerity/bunkerweb#2219]
### What happened?

After upgrading from 1.5.12 to 1.6.1, the scheduler is unable to update the configuration and bunkerweb complains that its IP is not in the whitelist:

```
2025/04/28 12:28:27 [warn] 922#922: *154 [API] can't validate access from IP 10.20.30.3 : IP is not in API_WHITELIST_IP, client: 10.20.30.3, server: bwapi, request: "GET /health HTTP/1.1", host: "bwapi"
```

### How to reproduce?

1. Set up Bunkerweb 1.5.12 using the docker-compose file bellow
2. Bump Bunkerweb's version to 1.6.1 and redeploy the compose stack

### Configuration file(s) (yaml or .env)

```YAML
version: '3'

services:
  bunkerweb:
    image: bunkerity/bunkerweb:${BUNKERWEB_VERSION:-latest}
    container_name: bunkerweb
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      AUTOCONF_MODE: "yes"
      API_WHITELIST_IP: "10.20.30.0/24"
      MULTISITE: "yes"
      DATABASE_URI: "mariadb+pymysql://bunkerweb:DB_PWDbw-db:3306/db"
      DISABLE_DEFAULT_SERVER: "yes"
      USE_REAL_IP: "yes"
      REAL_IP_FROM: "192.168.0.0/16 172.18.0.0/16"
      REAL_IP_HEADER: "X-Forwarded-For"
      WHITELIST_IP: "192.168.0.1 192.168.1.254 192.168.0.0/16"
      INTERCEPTED_ERROR_CODES: "405 413 429 500 501 502 503 504"
      AUTO_LETS_ENCRYPT: "yes"
      SERVE_FILES: "no"
      ALLOWED_METHODS: "GET|POST|PUT|PATCH|DELETE|HEAD"
      CUSTOM_HEADER: "X-Robots-Tag: none, noai"

    labels:
      - "bunkerweb.INSTANCE=yes"
    networks:
      - bw-universe
      - bw-services
    restart: unless-stopped

  bw-autoconf:
    depends_on:
      - bunkerweb
      - bw-docker
    image: bunkerity/bunkerweb-autoconf:${BUNKERWEB_VERSION:-latest}
    container_name: bunkerweb-autoconf
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:DB_PWD@bw-db:3306/db
      - AUTOCONF_MODE=yes
      - DOCKER_HOST=tcp://bw-docker:2375
    restart: unless-stopped
    networks:
      - bw-universe
      - bw-docker

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:${BUNKERWEB_VERSION:-latest}
    container_name: bunkerweb-scheduler
    depends_on:
      - bunkerweb
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:DB_PWD@bw-db:3306/db
      - DOCKER_HOST=tcp://bw-docker:2375
      - AUTOCONF_MODE=yes
    volumes:
      - letsencrypt:/var/cache/bunkerweb/letsencrypt
    networks:
      - bw-universe
      - bw-docker
    restart: unless-stopped

  bw-docker:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: bunkerweb-docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

  bw-db:
    image: mariadb:10.10
    container_name: bunkerweb-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=bunkerweb
      - MYSQL_PASSWORD=DB_PWD
    volumes:
      - bunkerweb-data:/var/lib/mysql
    networks:
      - bw-docker
    restart: unless-stopped

volumes:
  bunkerweb-data:
  letsencrypt:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```

### Relevant log output

```shell
2025/04/28 12:28:27 [warn] 922#922: *154 [API] can't validate access from IP 10.20.30.3 : IP is not in API_WHITELIST_IP, client: 10.20.30.3, server: bwapi, request: "GET /health HTTP/1.1", host: "bwapi"
```

### BunkerWeb version

1.6.1

### What integration are you using?

Docker

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by axeleroy** [comment]
Hello,

I did not know the existence of this guide, maybe it should be mentioned [in the release](https://github.com/bunkerity/bunkerweb/releases/tag/v1.6.0)? I'll follow the guide and report back.

**Comment by TheophileDiot** [comment]
Indeed it isn't mentioned, although we always recommended reading the `Upgrading` section before updating BunkerWeb 😄

**Comment by axeleroy** [comment]
Oops, now the database migration failed. [_bunkerweb-scheduler_logs.txt](https://github.com/user-attachments/files/19955706/_bunkerweb-scheduler_logs.txt)

Here is my updated `docker-compose.yaml`:

```yaml
x-bw-env: &bw-env
  AUTOCONF_MODE: "yes"
  API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
  DATABASE_URI: "mariadb+pymysql://bunkerweb:DB_PWD@bw-db:3306/db"


services:
  bunkerweb:
    image: bunkerity/bunkerweb:${BUNKERWEB_VERSION:-latest}
    container_name: bunkerweb
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      <<: *bw-env
    labels:
      - "bunkerweb.INSTANCE=yes"
    networks:
      - bw-universe
      - bw-services
    restart: unless-stopped

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:${BUNKERWEB_VERSION:-latest}
    container_name: bunkerweb-scheduler
    depends_on:
      - bunkerweb
      - bw-docker
    environment:
      <<: *bw-env
      BUNKERWEB_INSTANCES: ""
      SERVER_NAME: ""
      AUTOCONF_MODE: "yes"
      MULTISITE: "yes"
      DISABLE_DEFAULT_SERVER: "yes"
      USE_REAL_IP: "yes"
      REAL_IP_FROM: "192.168.0.0/16 172.18.0.0/16"
      REAL_IP_HEADER: "X-Forwarded-For"
      WHITELIST_IP: "192.168.0.1 192.168.1.254 192.168.0.0/16"
      INTERCEPTED_ERROR_CODES: "405 413 429 500 501 502 503 504"
      AUTO_LETS_ENCRYPT: "yes"
      SERVE_FILES: "no"
      ALLOWED_METHODS: "GET|POST|PUT|PATCH|DELETE|HEAD"
      CUSTOM_HEADER: "X-Robots-Tag: none, noai"
    volumes:
      - letsencrypt:/var/cache/bunkerweb/letsencrypt
      - bunkerweb-storage:/data
    networks:
      - bw-universe
      - bw-docker
    restart: unless-stopped

  bw-autoconf:
    depends_on:
      - bunkerweb
      - bw-docker
    image: bunkerity/bunkerweb-autoconf:${BUNKERWEB_VERSION:-latest}
    container_name: bunkerweb-autoconf
    environment:
      <<: *bw-env
      DOCKER_HOST: "tcp://bw-docker:2375"
    restart: unless-stopped
    networks:
      - bw-universe
      - bw-docker  

  bw-docker:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: bunkerweb-docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: "1"
      LOG_LEVEL: "warning"
    networks:
      - bw-docker
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped

  bw-db:
    image: mariadb:10.10
    container_name: bunkerweb-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "DB_PWD"
    volumes:
      - bunkerweb-data:/var/lib/mysql
    networks:
      - bw-docker
    restart: unless-stopped

volumes:
  bunkerweb-data:
  bunkerweb-storage:
  letsencrypt:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```
