### ISSUE TITLE
[BUG] Regexp are very slow if there is a yaml comment at the end of the line

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#232]
**Description**
Huge performance issue and memory usage is there is a yaml comment at the end of an environement variable.

**How to reproduce**
just add 
`PROXY_REAL_IP_FROM=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 104.16.0.0/12 108.162.192.0/18 131.0.72.0/22 141.101.64.0/18 162.158.0.0/15 172.64.0.0/13 173.245.48.0/20 188.114.96.0/20 190.93.240.0/20 197.234.240.0/22 198.41.128.0/17 2400:cb00::/32 2606:4700::/32 2803:f800::/32 2405:b500::/32 2405:8100::/32 2c0f:f248::/32 2a06:98c0::/29 #cloudflare ips` 
on the tmp/variable.env and run the gen/test.txt cmd.
- It's take up to 10 minutes to match the regexp !
- remove the yaml comment at the end ==> 0.6secs

I take realy long time to debug this, why should show a warning if there is a yaml comment at the end of a line.

Warning ! Avoid using yaml commentary at the end of variable '#' ==> huge speed impact in some circonstances.
**Logs**

**Comment by thelittlefireman** [comment]
More over : 
`^(\\d+.\\d+.\\d+.\\d+(/\\d+)? ?)*$` is verrryyy slow with re python module compare with :

`^((((\\d{1,3}.\\d{1,3}.\\d{1,3}.\\d{1,3}(/\\d+)?)|(([0-9A-Ea-z]{0,4})::?){1,7}([0-9a-z]{0,4})(/\\d+)?) ?))*$"`

**Comment by fl0ppy-d1sk** [comment]
Hello @thelittlefireman,

Here is what I tested :
```yaml
version: '3'

services:

  comment:
    image: alpine
    command: sh -c "chmod +x /opt/debug.sh && /opt/debug.sh"
    volumes:
      - ./debug.sh:/opt/debug.sh
    environment:
      - COMMENT_END_OF_LINE=test with comment # at the end of the line
      - COMMENT_END_OF_LINE_NO_SPACE=test with comment with no space #at the end of the line
      - COMMENT_END_OF_LINE_NO_SPACE_AT_ALL=test with comment with no space at all#at the end of the line
      - COMMENT_END_OF_LINE_SINGLE_SPACE=test with comment with no space at all# at the end of the line
```

Content of  `debug.sh` : 
```sh
#!/bin/sh
echo "$COMMENT_END_OF_LINE / $COMMENT_END_OF_LINE_NO_SPACE"
echo "$COMMENT_END_OF_LINE_NO_SPACE_AT_ALL / $COMMENT_END_OF_LINE_SINGLE_SPACE"
```

Result is : 
```
comment_1  | test with comment / test with comment with no space
comment_1  | test with comment with no space at all#at the end of the line / test with comment with no space at all# at the end of the line
```

Looks like if the # has no space to the left it won't be taken as a comment. It's not the case for the actual examples in the repository (maybe it was from the previous version ?).
