### ISSUE TITLE
[BUG] Dependencies tend to be old

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerweb#234]
**Description**
Alpine/debian packages are not up-to-date if there is no activity on the repository

**How to reproduce**
The version 1.3.2 is a bit old now and docker container still get old dependencies (openssl) please add 
please change github actions to 
```
on:
  schedule:
    - cron: '00 0 * * *'
  push:
    branches: [dev, master]
```
for getting new build every days.

**Logs**
The logs generated by bunkerized-nginx. **DON'T FORGET TO REMOVE PRIVATE DATA LIKE IP ADDRESSES !**
