### ISSUE TITLE
[BUG] Failed to dump the database using bwcli plugin backup

### ISSUE THREAD

**Issue by fazrulpratamaarhan** [bunkerity/bunkerweb#2350]
### What happened?

running :  `docker exec -it bunkerweb-bw-scheduler-1 bwcli plugin backup save`
got error : `Failed to dump the database: WARNING: option --ssl-verify-server-cert is disabled, because of an insecure passwordless login.`

![Image](https://github.com/user-attachments/assets/37390979-0d6a-42cb-931e-6482f97b01dd)

### How to reproduce?

running :  `docker exec -it bunkerweb-bw-scheduler-1 bwcli plugin backup save`

### Configuration file(s) (yaml or .env)

```YAML
bunkerweb:
    image: bunkerity/bunkerweb:1.6.1
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp" # QUIC
    environment:
      AUTOCONF_MODE: "yes"
      API_WHITELIST_IP: "127.0.0.0/24 10.20.30.0/24"
      USE_REDIS: "yes"
      REDIS_HOST: "ip_of_your_redis" # Replace with the actual IP or hostname of your Redis container
      REDIS_PORT: "6399"
      REDIS_DATABASE: "0"
      REDIS_PASSWORD: "password" # Remember to set a stronger password for Redis
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-services
    logging:
      driver: syslog
      options:
        tag: "bunkerweb" # This will be the tag used by syslog-ng to create the log file
        syslog-address: "udp://10.20.30.254:514" # This is the syslog-ng container address
```

### Relevant log output

```shell
[2025-06-04 18:57:25 +0700] [BACKUP] [161111] [ℹ️ ] - ✅ Database connection established
[2025-06-04 18:57:25 +0700] [BACKUP] [161111] [ℹ️ ] - Backing up 26 tables defined in the model
[2025-06-04 18:57:25 +0700] [BACKUP] [161111] [ℹ️ ] - Creating a backup for the MariaDB/MySQL database ...
[2025-06-04 18:57:26 +0700] [BACKUP] [161111] [❌] - Failed to dump the database: WARNING: option --ssl-verify-server-cert is disabled, because of an insecure passwordless login.
mariadb-dump: Error 2013: Lost connection to server during query when dumping table `bw_jobs_cache` at row: 26

[2025-06-04 18:57:26 +0700] [CLI] [161110] [❌] - CLI command status : ❌ (fail)
```

### BunkerWeb version

1.6.1

### What integration are you using?

Docker

### Linux distribution (if applicable)

Rocky Linux 9.5 (Blue Onyx)

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by TheophileDiot** [comment]
Hi @fazrulpratamaarhan, thank you for opening this issue. Can you tell us a bit more about the database you're using ? Does it uses TLS ?

**Comment by fazrulpratamaarhan** [comment]
> Hi [@fazrulpratamaarhan](https://github.com/fazrulpratamaarhan), thank you for opening this issue. Can you tell us a bit more about the database you're using ? Does it uses TLS ?

i think the database is not using tls, i use quickstart-guide docker autoconf
but my blocked request like 500K 
maybe need some tweak, because the database is large?

my database :

```
  bw-db:
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "password" # Remember to set a stronger password for the database
    command: --max_allowed_packet=128M # Increase the max allowed packet size for large data transfers      
    volumes:
      - bw-data:/var/lib/mysql
    restart: "unless-stopped"
    networks:
      - bw-db
```


my server specification :
8 core
16 gb ram
