### ISSUE TITLE
[BUG] Invalid path to letsencrypt certificate

### ISSUE THREAD

**Issue by svmrw** [bunkerity/bunkerweb#2461]
### What happened?

An existing certificate could not be found, so example.org does not use ssl
```
2025/06/29 19:22:57 [error] 57#57: [LETSENCRYPT] error while reading files : /var/cache/bunkerweb/letsencrypt/etc/live/org/fullchain.pem = /var/cache/bunkerweb/letsencrypt/etc/live/org/fullchain.pem: No such file or directory
2025/06/29 19:22:57 [error] 57#57: [INIT] letsencrypt:init() call failed : error reading files
```

### How to reproduce?

The certificate itself has been received and exists
```
/var/lib/docker/volumes/bw-storage/_data/cache/letsencrypt/etc/live/example.org/fullchain.pem
```
Somewhere an incorrect path is generated and "example.org" is cut off to "org"

### Configuration file(s) (yaml or .env)

```YAML
x-bw-env: &bw-env
  API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
  DATABASE_URI: "mariadb+pymysql://bunkerweb:password@bw-db:3306/bunkerweb"

name: bunkerweb

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.1
    container_name: bunkerweb
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp"
    environment:
      <<: *bw-env
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-services
      - proxy

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.1
    container_name: bw-scheduler
    environment:
      <<: *bw-env

      BUNKERWEB_INSTANCES: "bunkerweb"
      MULTISITE: "yes"
      SERVER_NAME: "bunkerweb example.org"
      USE_REVERSE_PROXY: yes
      USE_GZIP: yes
      USE_BROTLI: yes
      REDIRECT_HTTP_TO_HTTPS: "yes"
      AUTO_REDIRECT_HTTP_TO_HTTPS: "yes"


      
      bunkerweb_IS_DRAFT: no
      bunkerweb_USE_TEMPLATE: ui
      bunkerweb_USE_CORS: yes
      bunkerweb_USE_CLIENT_CACHE: yes
      bunkerweb_INTERCEPTED_ERROR_CODES: "400 404 405 413 429 500 501 502 503 504"
      bunkerweb_USE_GZIP: yes
      bunkerweb_KEEP_UPSTREAM_HEADERS: Content-Security-Policy Strict-Transport-Security X-Frame-Options X-Content-Type-Options Referrer-Policy
      bunkerweb_MAX_CLIENT_SIZE: 50m
      bunkerweb_SERVE_FILES: no
      bunkerweb_USE_REVERSE_PROXY: yes
      bunkerweb_REVERSE_PROXY_HOST: http://bw-ui:7000
      bunkerweb_REVERSE_PROXY_KEEPALIVE: yes
      bunkerweb_USE_UI: yes

      
      example.org_REVERSE_PROXY_HOST: "http://example-nginx:80"
      example.org_AUTO_LETS_ENCRYPT: "yes"
      example.org_LETS_ENCRYPT_CHALLENGE: "dns"
      example.org_LETS_ENCRYPT_DNS_PROVIDER: "cloudflare"
      example.org_USE_LETS_ENCRYPT_WILDCARD: "yes"
      example.org_LETS_ENCRYPT_DNS_CREDENTIAL_ITEM: 'dns_cloudflare_api_token = 12345'
      example.org_USE_REAL_IP: "yes"
    volumes:
      - bw-storage:/data
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-db

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.6.1
    container_name: bw-ui
    environment:
      <<: *bw-env
      OVERRIDE_ADMIN_CREDS: "yes"
      ADMIN_USERNAME: "user"
      ADMIN_PASSWORD: "pass8+"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-db

  bw-db:
    image: mariadb:11
    container_name: bw-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "bunkerweb"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "password"
    volumes:
      - bw-data:/var/lib/mysql
    restart: "unless-stopped"
    networks:
      - bw-db

volumes:
  bw-data:
    name: bw-data
  bw-storage:
    name: bw-storage

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db
  proxy:
    driver: bridge
    name: proxy
```

### Relevant log output

```shell
2025/06/29 19:22:57 [error] 57#57: [LETSENCRYPT] error while reading files : /var/cache/bunkerweb/letsencrypt/etc/live/org/fullchain.pem = /var/cache/bunkerweb/letsencrypt/etc/live/org/fullchain.pem: No such file or directory
2025/06/29 19:22:57 [error] 57#57: [INIT] letsencrypt:init() call failed : error reading files
```

### BunkerWeb version

1.6.1

### What integration are you using?

Docker

### Linux distribution (if applicable)

Ubuntu Server 24.04.2

### Removed private data

- [x] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
