### ISSUE TITLE
[BUG] Letsencrypt challenge repeatedly fails

### ISSUE THREAD

**Issue by Brawdunoir** [bunkerity/bunkerweb#258]
**Description**
Get Letsencrypt certificates in a multisite setup, using docker-autoconf, result in a fail loop.

**How to reproduce**
2 docker-compose files. One for the bunkerweb service (and autoconf). The other with the service.
Setup DNS records for the site addresses and forward ports 80 and 443 to the server.

```
#bw
version: '3.5'

services:
  mybunker:
    image: bunkerity/bunkerweb:dev
    container_name: mybunker
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - bw-data:/data
    environment:
      - MULTISITE=yes
      - SERVER_NAME=mysite.xyz
      - AUTO_LETS_ENCRYPT=yes
      - USE_LETS_ENCRYPT_STAGING=yes
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
    labels:
      - "bunkerweb.AUTOCONF"
    networks:
      - bw-autoconf
      - bw-services

  myautoconf:
    image: bunkerity/bunkerweb-autoconf:dev
    container_name: myautoconf
    restart: always
    volumes:
      - bw-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - bw-autoconf

volumes:
  bw-data:

networks:
  bw-autoconf:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
    ```

```
#service
version: '3'

services:
  myapp1:
    image: nginxdemos/hello:plain-text
    networks:
      bw-services:
        aliases:
          - myapp1
    labels:
      - "bunkerweb.SERVER_NAME=service.mysite.xyz"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_URL=/"
      - "bunkerweb.REVERSE_PROXY_HOST=http://myapp1"

networks:
  bw-services:
    external:
      name: bw-services
      ```

**Logs**
[logs.txt](https://github.com/bunkerity/bunkerweb/files/8885664/logs.txt)

**Comment by fl0ppy-d1sk** [comment]
Hello @Brawdunoir,

It should be fixed in the last 1.4.1 version. Please note that you will need to remove the volume mount from BunkerWeb container and add `AUTOCONF_MODE=yes` setting to BunkerWeb container. See the [updated documentation](https://docs.bunkerweb.io/1.4/integrations/#docker-autoconf) for more information.

**Comment by Brawdunoir** [comment]
Hello @fl0ppy-d1sk,
Seems like now the certificate request completes successfully, but the certificate cannot be loaded (if not due to renewal) nor deleted by the instances.
```
…
rm: can't remove '/data/letsencrypt/archive/myservice.mysite.xyz/cert1.pem': Permission denied
rm: can't remove '/data/letsencrypt/archive/myservice.mysite.xyz/fullchain1.pem': Permission denied
rm: can't remove '/data/letsencrypt/archive/myservice.mysite.xyz/chain1.pem': Permission denied
rm: can't remove '/data/letsencrypt/archive/myservice.mysite.xyz/privkey1.pem': Permission denied
rm: can't remove '/data/letsencrypt/live/myservice.mysite.xyz/README': Permission denied
rm: can't remove '/data/letsencrypt/live/myservice.mysite.xyz/cert.pem': Permission denied
rm: can't remove '/data/letsencrypt/live/myservice.mysite.xyz/fullchain.pem': Permission denied
rm: can't remove '/data/letsencrypt/live/myservice.mysite.xyz/chain.pem': Permission denied
rm: can't remove '/data/letsencrypt/live/myservice.mysite.xyz/privkey.pem': Permission denied
…
[emerg] 180#180: cannot load certificate "/etc/letsencrypt/live/mysite.xyz/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/mysite.xyz/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
…
```
This is my updated docker-compose file. I changed to a docker volume instead of a mount one and I added theAUTOCONF_MODE=yes.

```
version: '3.5'

services:
  mybunker:
    image: bunkerity/bunkerweb:1.4.1
    container_name: mybunker
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - bw-data:/data
    environment:
      - MULTISITE=yes
      - AUTOCONF_MODE=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=yes
      - SERVER_NAME=mysite.fr
      - WHITELIST_COUNTRY=fr
      - SERVE_FILES=no
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
    labels:
      - "bunkerweb.AUTOCONF"
    networks:
      - bw-autoconf
      - bw-services

  myautoconf:
    image: bunkerity/bunkerweb-autoconf:1.4.1
    container_name: myautoconf
    restart: always
    volumes:
      - bw-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - bw-autoconf

networks:
  bw-autoconf:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
volumes:
  bw-data:
```

Full logs: [logs.txt](https://github.com/bunkerity/bunkerweb/files/8934785/logs2.txt)


PS: I wasn’t able to reuse my manually requested certificates that I used before from the mount volume due to the same « cannot load certificate » error.

**Comment by fl0ppy-d1sk** [comment]
Hello @Brawdunoir,

You don't have to mount the bw-data folder in the BunkerWeb container but only in the autoconf one.

Documentation has been been updated in 1.4.1 to reflect that change : 
```yaml
version: '3'

services:

  mybunker:
    image: bunkerity/bunkerweb:1.4.1
    ports:
      - 80:8080
      - 443:8443
    environment:
      - AUTOCONF_MODE=yes
      - MULTISITE=yes
      - SERVER_NAME=
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
    labels:
      - "bunkerweb.AUTOCONF"
    networks:
      - bw-autoconf
      - bw-services

  myautoconf:
    image: bunkerity/bunkerweb-autoconf:1.4.1
    volumes:
      - bw-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - bw-autoconf

volumes:
  bw-data:

networks:
  bw-autoconf:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
```
