### ISSUE TITLE
[BUG] SERVE_FILES not working in docker-autoconf mode

### ISSUE THREAD

**Issue by Silur** [bunkerity/bunkerweb#280]
`bunkerweb.SERVE_FILES` is not hosting the `ROOT_FOLDER` content when configured with autoconf. In a standalone bunkerweb instance however it works.

With autoconf, `myserver.com` in the example config below shows the bunkerweb-flavored 404 (not the nginx default)

Dockerfile
```
FROM debian:latest
COPY --chown=www-data:www-data ./dist /opt/bunkerweb/www/myserver.com
ENTRYPOINT ["tail", "-f", "/dev/null"]
```

And the following docker-compose (with bunkerweb and autoconf already running and hosting a couple other services):

docker-compose.yml
```
version: '3.1'
networks:
  stack:
    name: stack
    external: false
  bw-services:
    name: bunker_bw-services
    external: true

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      network: stack
    restart: always
    networks:
      - stack
      - bw-services
    labels:
      - "bunkerweb.SERVER_NAME=myserver.com"
      - "bunkerweb.SERVE_FILES=yes"
      - "bunkerweb.ROOT_FOLDER=/opt/bunkerweb/www/myserver.com" #just in case
      - "bunkerweb.ALLOWED_METHODS=GET|POST|HEAD|OPTIONS|PATCH"
      - "bunkerweb.LIMIT_REQ_RATE=12r/s"  
 ```
