### ISSUE TITLE
[BUG] CORS Error

### ISSUE THREAD

**Issue by amrap030** [bunkerity/bunkerweb#283]
Hello,

I am trying to use Bunkerweb as a reverse proxy to route traffic from a subdomain to the corresponding application. This is my `docker-compose.yml` file, which I created with the help of the configurator:

```yml
version: "3"
services:
  mybunker:
    image: bunkerity/bunkerweb:1.4.2
    ports:
      - 80:8080
      - 443:8443
    environment:
      - MULTISITE=yes
      - SERVER_NAME=
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - AUTOCONF_MODE=yes
      - DISABLE_DEFAULT_SERVER=yes
      - LOG_LEVEL=debug
    labels:
      - "bunkerweb.AUTOCONF"
    networks:
      - bw-autoconf
      - bw-services

  myautoconf:
    image: bunkerity/bunkerweb-autoconf:1.4.2
    volumes:
      - ./bw-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - bw-autoconf

  api_magic-mondrian_art:
    image: amrap030/whitelabel-backend
    ports:
      - 8081
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - /opt/mondrians/config.js:/usr/src/config.js
    networks:
      bw-services:
        aliases:
          - api_magic-mondrian_art
    labels:
      - "bunkerweb.SERVER_NAME=api.magic-mondrian.art"
      - "bunkerweb.USE_CLIENT_CACHE=yes"
      - "bunkerweb.USE_GZIP=yes"
      - "bunkerweb.AUTO_LETS_ENCRYPT=yes"
      - "bunkerweb.EMAIL_LETS_ENCRYPT=***@t-online.de"
      - "bunkerweb.REDIRECT_HTTP_TO_HTTPS=yes"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.USE_PROXY_CACHE=yes"
      - "bunkerweb.REVERSE_PROXY_URL=/"
      - "bunkerweb.REVERSE_PROXY_HOST=http://api_magic-mondrian_art:8081"
      - "bunkerweb.USE_MODSECURITY=no"
      - "bunkerweb.COOKIE_FLAGS=* SameSite=Lax"
      - "bunkerweb.USE_LETS_ENCRYPT_STAGING=yes"

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - 6379
    restart: unless-stopped
    networks:
      bw-services:
        aliases:
          - redis_magic-mondrian_art

volumes:
  bw-confs:

networks:
  bw-autoconf:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:

```

The certificate creation is working. When I make a request to the url, it first makes an OPTIONS request which succeeds, but it doesn't return the corresponding Headers, which results into a CORS Error. My application has setup CORS correct, so nginx or bunkerweb seems to be the bottleneck here. I am not even receiving the request in my application because of the CORS error.

I already tried this https://github.com/bunkerity/bunkerweb/issues/24 with no luck.

So what am I doing wrong?
