### ISSUE TITLE
[DOC] Add configuration template for Vikunja

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [bunkerity/bunkerweb#322]
Vikunja can be reverse proxied by BunkerWeb like this:

```yml
version: '3'

services:
  db:
    image: mariadb:10
    networks:
      - vikunja_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: vikunja
    volumes:
      - ${CONFIG_FOLDER}/vikunja/mysql:/var/lib/mysql
    restart: unless-stopped
  api:
    image: vikunja/api
    networks:
      - vikunja_network
      - services
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: secret
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: supersecret
      VIKUNJA_SERVICE_FRONTENDURL: https://vikunja.youtdomain.com/
    volumes: 
      - ${CONFIG_FOLDER}/vikunja/api:/app/vikunja/files
      - ${CONFIG_FOLDER}/vikunja/config:/.config
    depends_on:
      - db
    restart: unless-stopped
    labels:
          - "bunkerweb.SERVER_NAME=vikunja.youtdomain.com"
          - "bunkerweb.ALLOWED_METHODS=GET|POST|HEAD|DELETE|PUT"
          - "bunkerweb.REVERSE_PROXY_URL=/"
          - "bunkerweb.REVERSE_PROXY_HOST=http://vikunja-frontend-1:80"
          - "bunkerweb.REVERSE_PROXY_URL_1=~* ^/(api|dav|[.]well[-]known)/"
          - "bunkerweb.REVERSE_PROXY_HOST_1=http://vikunja-api-1:3456"
          - "bunkerweb.MAX_CLIENT_SIZE_1=20M"
          - "bunkerweb.REVERSE_PROXY_WS=yes"
          - "bunkerweb.REVERSE_PROXY_WS_1=yes"

  frontend:
    image: vikunja/frontend
    restart: unless-stopped
    networks:
      - vikunja_network
      - services

networks:
    vikunja_network:
        name: vikunja
        ipam:
          driver: default
          config:
            - subnet: 172.22.0.0/24
    services:
      name: services
      external: true
```
