### ISSUE TITLE
[BUG] slower response time compared to bunkerized-nginx

### ISSUE THREAD

**Issue by BigNerd95** [bunkerity/bunkerweb#427]
**Description**
Making a curl https request to a small static file on the same machine takes:
- with bunkerized-nginx: ~24ms
- with bunkerweb: ~57ms

**How to reproduce**
Setup a simple config serving static files and disable all blocking features
###### bunkerized-nginx
```
version: '3'

services:
    web:
        image: bunkerity/bunkerized-nginx:1.3.2
        ports:
            - 80:8080
            - 443:8443
        volumes: 
            - ./www:/www:ro
            - ./certs:/etc/letsencrypt
        environment:
            - SERVE_FILES=yes     
            - DISABLE_DEFAULT_SERVER=yes 
            - SERVER_NAME=bubkerized-nginx.this.vps.domain.com
            - AUTO_LETS_ENCRYPT=yes
            - REDIRECT_HTTP_TO_HTTPS=yes
            - USE_GZIP=yes
           
            - USE_FAIL2BAN=no
            - USE_CLAMAV_SCAN=no
            - CLAMAV_SCAN_REMOVE=no
            - USE_CLAMAV_UPLOAD=no
            - BLOCK_PROXIES=no
            - USE_DNSBL=no
            - BLOCK_ABUSERS=no
            - BLOCK_USER_AGENT=no
            - USE_REMOTE_API=no
            - USE_MODSECURITY_CRS=no


            - USE_BAD_BEHAVIOR=yes
            - BAD_BEHAVIOR_STATUS_CODES=403 404
            - BAD_BEHAVIOR_THRESHOLD=100
            - BAD_BEHAVIOR_BAN_TIME=300
            - BAD_BEHAVIOR_COUNT_TIME=60
            
```

###### bunkerweb
```
version: "3"

services1:
  web1:
    image: bunkerity/bunkerweb:1.4.7
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./bw-data:/data
    environment:
      - SERVE_FILES=yes
      - DISABLE_DEFAULT_SERVER=yes
      - SERVER_NAME=bubkerweb.this.vps.domain.com    
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - USE_GZIP=yes


      - USE_BLACKLIST=no
      - USE_DNSBL=no
      - USE_API=no
      - USE_BUNKERNET=no
      - USE_ANTIBOT=no
      - USE_MODSECURITY_CRS=no

      - USE_BAD_BEHAVIOR=yes
      - BAD_BEHAVIOR_BAN_TIME=300
      - BAD_BEHAVIOR_STATUS_CODES=403 404
      - BAD_BEHAVIOR_THRESHOLD=100
      - BAD_BEHAVIOR_COUNT_TIME=60

```

**Logs**
###### bunkerized-nginx
```
user@VPS:~$ time curl https://bubkerized-nginx.this.vps.domain.com/small_static_file
test bunkerized-nginx

real	0m0.024s
user	0m0.013s
sys	0m0.008s
```

###### bunkerweb
```
user@VPS:~$ time curl https://bubkerweb.this.vps.domain.com/small_static_file
test bunkerweb

real	0m0.057s
user	0m0.048s
sys	0m0.000s
```
