### ISSUE TITLE
[BUG] Issue with Cloudflare wildcard

### ISSUE THREAD

**Issue by killmasta93** [bunkerity/bunkerweb#461]
Hi
Currently trying to use https://github.com/bunkerity/bunkerweb/tree/master/examples/certbot-dns-cloudflare
```
which in the docker compose it says 
      - CUSTOM_HTTPS_CERT=/certs/live/example.com/fullchain.pem
      - CUSTOM_HTTPS_KEY=/certs/live/example.com/privkey.pem
```
Which is giving the wild card but when i go to domain.com im getting the ssl not verified but if i go to app.domain.com it works 
this is part of my docker compose

 ```
version: '3'
services:
  mybunker:
    image: bunkerity/bunkerweb:1.4.8
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - bw-data:/data
      - certs:/certs
    environment:
      - SERVER_NAME=mydomain.com app.mydomain.com
      - MULTISITE=yes
      - USE_CUSTOM_HTTPS=yes
      - CUSTOM_HTTPS_CERT=/certs/live/mydomain.com/fullchain.pem
      - CUSTOM_HTTPS_KEY=/certs/live/mydomain.com/privkey.pem
      - mydomain.com_USE_LIMIT_REQ=no
      - mydomain.com_USE_LIMIT_CONN=no
      - mydomain.com_USE_REVERSE_PROXY=yes
      - mydomain.com_REVERSE_PROXY_KEEPALIVE=yes
      - mydomain.com_REVERSE_PROXY_URL=/
      - mydomain.com_REVERSE_PROXY_HOST=http://192.168.7.189:8084
      - app.mydomain.com_USE_CLIENT_CACHE=yes
      - app.mydomain.com_USE_GZIP=yes
      - app.mydomain.com_USE_LIMIT_REQ=no
      - app.mydomain.com_USE_LIMIT_CONN=no
      - app.mydomain.com_USE_REVERSE_PROXY=yes
      - app.mydomain.com_REVERSE_PROXY_KEEPALIVE=yes
      - app.mydomain.com_REVERSE_PROXY_URL=/
      - app.mydomain.com_REVERSE_PROXY_HOST=http://192.168.7.189:8083
      - USE_CROWDSEC=yes
      - CROWDSEC_API=http://crowdsec:8080
      - CROWDSEC_API_KEY=s3cr3tb0unc3rk3y20
      - USE_CLAMAV=yes
      - CLAMAV_API=http://clamav-api:8000
    networks:
      - mailcowdockerized_mailcow-network
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.22.1.251:514"


  mycertbot:
    image: certbot/dns-cloudflare
    environment:
      - DOMAINS=*.mydomain.com
      - EMAIL=ssl@mydomain.co
    volumes:
      - certs:/etc/letsencrypt
      - ./cloudflare.ini:/opt/cloudflare.ini
      - ./entrypoint.sh:/opt/entrypoint.sh
    entrypoint: /bin/sh /opt/entrypoint.sh

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    volumes:
      - cs-data:/var/lib/crowdsec/data
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - bw-logs:/var/log:ro
    environment:
      - BOUNCER_KEY_bunkerweb=s3cr3tb0unc3rk3y20
      - COLLECTIONS=crowdsecurity/nginx
    networks:
      - mailcowdockerized_mailcow-network

  syslog:
    image: balabit/syslog-ng:3.36.1
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - bw-logs:/var/log
    networks:
      mailcowdockerized_mailcow-network:
        ipv4_address: 172.22.1.251

  clamav-api:
    image: bunkerity/bunkerweb-clamav
    environment:
      - CLAMAV_HOST=clamav
      - REDIS_HOST=redis

  clamav:
    image: clamav/clamav:0.104
    volumes:
      - ./clamav-data:/var/lib/clamav


  redis:
    image: redis:7-alpine

volumes:
  bw-data:
  bw-logs:
  cs-data:
  certs:
networks:
  mailcowdockerized_mailcow-network:
    external:
      name: mailcowdockerized_mailcow-network
```

Thank you
