### ISSUE TITLE
[BUG] no trash button on webGUI

### ISSUE THREAD

**Issue by farzadha2** [bunkerity/bunkerweb#597]
**Description**
Hi Currently no trash button on webGui to delete 
also every service that is created keeps showing the example.com 
Currently using 1.5.1

![image](https://github.com/bunkerity/bunkerweb/assets/62571297/05d39e15-21b3-47e1-af1d-330d2fea6b4f)

Thank you

**Comment by TheophileDiot** [comment]
Hi @farzadha2, thank you opening this issue, could you provide us your configuration by any chance and also if there are any, the steps to reproduce your bug ? Thank you 🙏

**Comment by farzadha2** [comment]
hi @TheophileDiot Thank you for the reply, sure this is my docker compose,
created from zero the instalacion 
```

version: "3.5"

services:
  mybunker:
    image: bunkerity/bunkerweb:1.5.1
    ports:
      - 80:8080
      - 443:8443
    environment:
      - SERVER_NAME=admin.domain.com # replace with your domain
      - MULTISITE=yes
      - AUTO_LETS_ENCRYPT=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - admin.domain.com_USE_UI=yes
      - admin.domain.com_SERVE_FILES=no
      - admin.domain.com_USE_REVERSE_PROXY=yes
      - admin.domain.com_REVERSE_PROXY_URL=/changeme # replace with another url
      - admin.domain.com_REVERSE_PROXY_HOST=http://bw-ui:7000
      - admin.domain.com_INTERCEPTED_ERROR_CODES=400 404 405 413 429 500 501 502 503 504
    labels:
      - "bunkerweb.INSTANCE"
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.1
    depends_on:
      - mybunker
    environment:
      - DOCKER_HOST=tcp://bw-docker-proxy:2375
    volumes:
      - bw-data:/data
    networks:
      - bw-universe
      - bw-docker

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.5.1
    depends_on:
      - bw-docker-proxy
    environment:
      - DOCKER_HOST=tcp://bw-docker-proxy:2375
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=mypassword# replace with a stronger password
    volumes:
      - bw-data:/data
    networks:
      - bw-universe
      - bw-docker

  bw-docker-proxy:
    image: tecnativa/docker-socket-proxy:0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

volumes:
  bw-data:
   driver: local-persist
   driver_opts:
     mountpoint: /waf/sites/bw-data



networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
  bw-docker:

```
