### ISSUE TITLE
[BUG] Unable to set reverse proxy to another VM ip when deployed as Docker.

### ISSUE THREAD

**Issue by dalso0418** [bunkerity/bunkerweb#685]
### What happened?

Hello. Thank you for the fantastic project.

I was using caddy, but I proceeded with the 1.5.2 version for functional testing. 1.5.2 has a problem that the new service is not registered, so the service registration has been completed with the :dev version.
However, if reverse proxy is specified here as ip for another vm, it does not work properly.

ex) Forward to reverse proxy 192.168.1.x:9000.
Similarly, if you specify 192.168.1.x:9000 for the reverse proxy in the bunker web, you get an X.

How do I set up the docker network to communicate with the internal network?

### How to reproduce?

Deploy as docker and enter another VM IP in reverse proxy

### Configuration file(s) (yaml or .env)
https://docs.bunkerweb.io/latest/web-ui/#installation

```YAML
version: "3.5"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:dev
    ports:
      - 80:8080
      - 443:8443
    labels:
      - "bunkerweb.INSTANCE"
    environment:
      - SERVER_NAME=www.example.com
      - MULTISITE=yes
      - DATABASE_URI=mariadb+pymysql://bunkerweb:changeme@bw-db:3306/db # Remember to set a stronger password for the database
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - www.example.com_USE_UI=yes
      - www.example.com_USE_REVERSE_PROXY=yes
      - www.example.com_REVERSE_PROXY_URL=/changeme
      - www.example.com_REVERSE_PROXY_HOST=http://bw-ui:7000
      - www.example.com_INTERCEPTED_ERROR_CODES=400 404 405 413 429 500 501 502 503 504
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:dev
    depends_on:
      - bunkerweb
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:changeme@bw-db:3306/db # Remember to set a stronger password for the database
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

  bw-ui:
    image: bunkerity/bunkerweb-ui:dev
    depends_on:
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:changeme@bw-db:3306/db # Remember to set a stronger password for the database
      - DOCKER_HOST=tcp://bw-docker:2375
      - ADMIN_USERNAME=changeme
      - ADMIN_PASSWORD=changeme # Remember to set a stronger password for the changeme user
    networks:
      - bw-universe
      - bw-docker

  bw-db:
    image: mariadb:10.10
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=bunkerweb
      - MYSQL_PASSWORD=changeme # Remember to set a stronger password for the database
    volumes:
      - bw-data:/var/lib/mysql
    networks:
      - bw-docker

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```

### Relevant log output

```shell
x
```

### BunkerWeb version

1.5.2

### What integration are you using?

Docker

### Linux distribution (if applicable)

Ubuntu server 22.04 LTS

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
