### ISSUE TITLE
clamav and virustotal plugin does't work

### ISSUE THREAD

**Issue by andyoulovexy** [bunkerity/bunkerweb#740]
### What happened?

![图片](https://github.com/bunkerity/bunkerweb/assets/38940994/2a21f5b6-0476-4f17-b900-6540c582fad9)
![图片](https://github.com/bunkerity/bunkerweb/assets/38940994/1252603d-e2df-4083-8415-8798a68a0228)

docker dev tag 
upload virus file .log include "403" forbidden,but i access my website use same ip

### How to reproduce?

use docker dev tag and clamav plugin

### Configuration file(s) (yaml or .env)

```YAML
version: "3.5"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:dev
    ports:
      - 80:8080
      - 443:8443
    labels:
      - "bunkerweb.INSTANCE"
    environment:
      - SERVER_NAME=suc.snagou.com
      - MULTISITE=yes
      - USE_CLAMAV=yes
      - CLAMAV_HOST=clamav
      #- USE_VIRUSTOTAL=yes
      #- VIRUSTOTAL_API=http://virustotal-api:8000
      - CLAMAV_API=http://clamav-api:8000
      - VIRUSTOTAL_API_KEY=xxxxxx
      - DATABASE_URI=mariadb+pymysql://bunkerweb:xxxx@bw-db:3306/db # Remember to set a stronger password for the database
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - suc.snagou.com_USE_UI=yes
      - suc.snagou.com_USE_REVERSE_PROXY=yes
      - suc.snagou.com_REVERSE_PROXY_URL=/xxxx
      - suc.snagou.com_REVERSE_PROXY_HOST=http://bw-ui:7000
      - suc.snagou.com_INTERCEPTED_ERROR_CODES=400 404 405 413 429 500 501 502 503 504
    networks:
      - bw-universe
      - bw-services
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.20.30.254:514"

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:dev
    volumes:
      - ./bw-data:/data
    depends_on:
      - bunkerweb
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:xxxxxx@bw-db:3306/db # Remember to set a stronger password for the database
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - LOG_LEVEL=warning
    networks:
      - bw-docker

  bw-ui:
    image: bunkerity/bunkerweb-ui:dev
    depends_on:
      - bw-docker
    environment:
      - DATABASE_URI=mariadb+pymysql://bunkerweb:xxxxx@bw-db:3306/db # Remember to set a stronger password for the database
      - DOCKER_HOST=tcp://bw-docker:2375
      - ADMIN_USERNAME=xxxxx
      - ADMIN_PASSWORD=xxxxx # Remember to set a stronger password for the Abc1234%Fsme user
    networks:
      - bw-universe
      - bw-docker

  crowdsec:
    image: crowdsecurity/crowdsec:v1.5.2
    volumes:
      - cs-data:/var/lib/crowdsec/data
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - bw-logs:/var/log:ro
      - /var/log/messages:/mnt/messages:ro
      - /var/log/secure:/mnt/secure:ro
    environment:
      - BOUNCER_KEY_bunkerweb=xxxxx
      - COLLECTIONS=crowdsecurity/nginx
    networks:
      - bw-universe

  syslog:
    image: balabit/syslog-ng:4.2.0
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - bw-logs:/var/log
    networks:
      bw-universe:
        ipv4_address: 10.20.30.254


  bw-db:
    image: mariadb:10.10
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=xxxxx
      - MYSQL_PASSWORD=xxxxx # Remember to set a stronger password for the database
    volumes:
      - bw-data:/var/lib/mysql
    networks:
      - bw-docker

  clamav:
    image: clamav/clamav:1.1
    volumes:
      - ./clamav-data:/var/lib/clamav
    networks:
      - bw-universe

  clamav-api:
    image: bunkerity/bunkerweb-clamav
    networks:
      - bw-universe
    environment:
      - CLAMAV_HOST=clamav
      - REDIS_HOST=redis

  virustotal-api:
    image: bunkerity/bunkerweb-virustotal
    environment:
      - API_KEY=xxxxxx
      - REDIS_HOST=redis
    networks:
      - bw-universe

  redis:
    image: redis:7-alpine
    networks:
      - bw-universe

volumes:
  bw-data:
  cs-data:
  bw-logs:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-docker:
    name: bw-docker
```

### Relevant log output

```shell
clamav log:
Mon Oct 30 09:24:01 2023 -> Limits: MaxHTMLNormalize limit set to 41943040 bytes.
Mon Oct 30 09:24:01 2023 -> Limits: MaxHTMLNoTags limit set to 8388608 bytes.
Mon Oct 30 09:24:01 2023 -> Limits: MaxScriptNormalize limit set to 20971520 bytes.
Mon Oct 30 09:24:01 2023 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Mon Oct 30 09:24:01 2023 -> Limits: MaxPartitions limit set to 50.
Mon Oct 30 09:24:01 2023 -> Limits: MaxIconsPE limit set to 100.
Mon Oct 30 09:24:01 2023 -> Limits: MaxRecHWP3 limit set to 16.
Mon Oct 30 09:24:01 2023 -> Limits: PCREMatchLimit limit set to 100000.
Mon Oct 30 09:24:01 2023 -> Limits: PCRERecMatchLimit limit set to 2000.
Mon Oct 30 09:24:01 2023 -> Limits: PCREMaxFileSize limit set to 104857600.
Mon Oct 30 09:24:01 2023 -> Archive support enabled.
Mon Oct 30 09:24:01 2023 -> AlertExceedsMax heuristic detection disabled.
Mon Oct 30 09:24:01 2023 -> Heuristic alerts enabled.
Mon Oct 30 09:24:01 2023 -> Portable Executable support enabled.
Mon Oct 30 09:24:01 2023 -> ELF support enabled.
Mon Oct 30 09:24:01 2023 -> Mail files support enabled.
Mon Oct 30 09:24:01 2023 -> OLE2 support enabled.
Mon Oct 30 09:24:01 2023 -> PDF support enabled.
Mon Oct 30 09:24:01 2023 -> SWF support enabled.
Mon Oct 30 09:24:01 2023 -> HTML support enabled.
Mon Oct 30 09:24:01 2023 -> XMLDOCS support enabled.
Mon Oct 30 09:24:01 2023 -> HWP3 support enabled.
Mon Oct 30 09:24:01 2023 -> Self checking every 600 seconds.
Mon Oct 30 09:24:01 2023 -> Set stacksize to 1048576
socket found, clamd started.
Mon Oct 30 09:32:16 2023 -> instream(10.20.30.1@37044): Win.Test.EICAR_HDB-1 FOUND
Mon Oct 30 09:34:13 2023 -> SelfCheck: Database status OK.
Mon Oct 30 09:34:58 2023 -> instream(10.20.30.1@37138): Win.Test.EICAR_HDB-1 FOUND
Mon Oct 30 09:37:24 2023 -> instream(10.20.30.1@37284): Win.Test.EICAR_HDB-1 FOUND
Mon Oct 30 09:44:16 2023 -> SelfCheck: Database status OK.
Mon Oct 30 09:54:18 2023 -> SelfCheck: Database status OK.
Mon Oct 30 10:04:21 2023 -> SelfCheck: Database status OK.
Mon Oct 30 10:14:24 2023 -> SelfCheck: Database status OK.
Mon Oct 30 10:24:27 2023 -> SelfCheck: Database status OK.
Mon Oct 30 10:34:29 2023 -> SelfCheck: Database status OK.
Mon Oct 30 10:44:32 2023 -> SelfCheck: Database status OK.
Mon Oct 30 10:54:35 2023 -> SelfCheck: Database status OK.
Mon Oct 30 11:04:38 2023 -> SelfCheck: Database status OK.
Mon Oct 30 11:14:41 2023 -> SelfCheck: Database status OK.
Mon Oct 30 11:20:28 2023 -> instream(10.20.30.1@39194): Win.Test.EICAR_HDB-1 FOUND
Mon Oct 30 11:24:44 2023 -> SelfCheck: Database status OK.
Mon Oct 30 11:34:46 2023 -> SelfCheck: Database status OK.
Mon Oct 30 11:44:49 2023 -> SelfCheck: Database status OK.
Mon Oct 30 11:54:52 2023 -> SelfCheck: Database status OK.
Mon Oct 30 12:04:55 2023 -> SelfCheck: Database status OK.
Mon Oct 30 12:14:58 2023 -> SelfCheck: Database status OK.
Mon Oct 30 12:15:18 2023 -> instream(10.20.30.1@40168): Win.Test.EICAR_HDB-1 FOUND


bunkerweb log:
2023/10/30 12:15:16 [error] 6198#6198: *1949 [UTILS] error while doing reverse DNS query for xxxx : failed to receive reply from UDP server 127.0.0.11:53: timeout, client: xxxx, server: xxxx.com, request: "GET /data/upload/image/20231030/1698650451259104.pdf HTTP/1.0", host: "xxxx.com", referrer: "http://xxxx.com/@yang/index.php?c=content&a=edit&id=40"
xxxx.com xxxx - - [30/Oct/2023:12:15:17 +0000] "GET /data/upload/image/20231030/1698650451259104.pdf HTTP/1.0" 304 0 "http://xxxx.com/@yang/index.php?c=content&a=edit&id=40" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"
2023/10/30 12:15:18 [warn] 6200#6200: *1956 [ACCESS] denied access from clamav : file with checksum d9305862fe0bf552718d19db43075d88cffd768974627db60fa1a90a8d45563e035a6449663b8f66aac53791d77f37dbb5035159aa08e69fc473972022f80010is detected : Win.Test.EICAR_HDB-1, client: xxxx, server: xxxx.com, request: "POST /@yang/index.php?c=uploadfile&a=ueditor&action=uploadfile HTTP/1.0", host: "xxxx.com", referrer: "http://xxxx.com/@yang/index.php?c=content&a=edit&id=40"
xxxx.com xxxx - - [30/Oct/2023:12:15:18 +0000] "POST /@yang/index.php?c=uploadfile&a=ueditor&action=uploadfile HTTP/1.0" 403 703540 "http://xxxx.com/@yang/index.php?c=content&a=edit&id=40" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"
2023/10/30 12:15:18 [notice] 6200#6200: *1960 [BADBEHAVIOR] increased counter for IP xxxx (1/10), context: ngx.timer, client: xxxx, server: 0.0.0.0:8080
2023/10/30 12:15:19 [notice] 6200#6200: *1959 [BUNKERNET] successfully reported IP xxxx (reason : unknown), context: ngx.timer, client: xxxx, server: 0.0.0.0:8080
xxxx.com xxxx - - [30/Oct/2023:12:15:19 +0000] "POST /@yang/index.php?c=content&a=edit&id=40 HTTP/1.0" 200 655 "http://xxxx.com/@yang/index.php?c=content&a=edit&id=40" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"
xxxx.com xxxx - - [30/Oct/2023:12:15:22 +0000] "GET /@yang/index.php?c=content&a=edit&id=40 HTTP/1.0" 200 4669 "http://xxxx.com/@yang/index.php?c=content&a=edit&id=40" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"
2023/10/30 12:16:18 [notice] 6200#6200: *1972 [BADBEHAVIOR] decreased counter for IP xxxx (0/10), context: ngx.timer, client: xxxx, server: 0.0.0.0:8080


clamav api log:

[2023-10-30 09:20:10] - uvicorn.access - ℹ️  - BunkerWeb ClamAV API started
[2023-10-30 09:23:28] - uvicorn.access - ℹ️  - BunkerWeb ClamAV API stopped
[2023-10-30 09:23:37] - uvicorn.access - ℹ️  - BunkerWeb ClamAV API started
```

### BunkerWeb version

1.5.2

### What integration are you using?

Docker

### Removed private data

- [X] I have removed all private data from the configuration file and the logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
