### ISSUE TITLE
[DOC] Web-UI K8S "Advanced Installation" bunkerweb-ui isn't using correct serviceaccount

### ISSUE THREAD

**Issue by Jobuen** [bunkerity/bunkerweb#871]
### Description

The bunkerweb-ui deployment given in the "Advanced Installation"-Kubernetes-template for using the Web UI is missing the service account name of the bunkerweb-serviceaccount created by the template. 

This leads to an error when the UI tries to query ressources when logging in, as it defaults to the default serviceaccount of the given namespace, which is missing the required permissions.

### Proposed solution (optional)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunkerweb-ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bunkerweb-ui
  template:
    metadata:
      labels:
        app: bunkerweb-ui
    spec:
      serviceAccountName: sa-bunkerweb ### Adding this fixes it.
      containers:
        - name: bunkerweb-ui
          image: bunkerity/bunkerweb-ui:1.5.5
          imagePullPolicy: Always
          env:
            - name: KUBERNETES_MODE
              value: "YES"
            - name: "DATABASE_URI"
              value: "mariadb+pymysql://bunkerweb:testor@svc-bunkerweb-db:3306/db" 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
